import type { MermaidConfig } from "mermaid";

export const MERMAID_CONFIG: MermaidConfig = {
  startOnLoad: false,
  theme: "base",
  securityLevel: "loose",
  fontFamily: "Inter, system-ui, sans-serif",
  sequence: {
    showSequenceNumbers: true,
    wrap: true,
    actorMargin: 80,
    messageMargin: 32,
    noteMargin: 20,
  },
  flowchart: {
    useMaxWidth: true,
    htmlLabels: true,
    curve: "basis",
  },
  themeVariables: {
    background: "#0f172a",
    primaryColor: "#111827",
    primaryTextColor: "#f8fafc",
    primaryBorderColor: "#6366f1",
    secondaryColor: "#0f766e",
    secondaryTextColor: "#ecfeff",
    secondaryBorderColor: "#5eead4",
    tertiaryColor: "#1e293b",
    tertiaryTextColor: "#cbd5e1",
    tertiaryBorderColor: "#475569",
    lineColor: "#a5b4fc",
    textColor: "#cbd5e1",
    mainBkg: "#111827",
    nodeBkg: "#111827",
    nodeTextColor: "#f8fafc",
    clusterBkg: "#0b1220",
    clusterBorder: "#334155",
    actorBkg: "#111827",
    actorBorder: "#6366f1",
    actorTextColor: "#f8fafc",
    actorLineColor: "#475569",
    signalColor: "#c4b5fd",
    signalTextColor: "#e2e8f0",
    labelBoxBkgColor: "#0f172a",
    labelBoxBorderColor: "#334155",
    labelTextColor: "#cbd5e1",
    loopTextColor: "#f8fafc",
    noteBkgColor: "#1e293b",
    noteBorderColor: "#475569",
    noteTextColor: "#cbd5e1",
    activationBorderColor: "#818cf8",
    activationBkgColor: "#312e81",
  },
};
