import type { AcademyManifest, AcademyRoute } from "./types/academy";

export type MockAcademyRoute = Omit<AcademyRoute, "component">;

export interface MockAcademy
  extends Omit<AcademyManifest, "routes" | "totalEstimatedMinutes"> {
  comingSoon?: boolean;
  externalUrl?: string;
  moduleCount: number;
  totalHours: number;
  routes: MockAcademyRoute[];
}

export const MOCK_ACADEMIES: MockAcademy[] = [
  {
    slug: "apollo-graphql",
    title: "Apollo GraphQL",
    description:
      "Master the Apollo ecosystem — client, server, caching, federation, and production patterns for modern GraphQL APIs.",
    version: "1.0.0",
    icon: "⚡",
    accentColor: "#e535ab",
    moduleCount: 32,
    totalHours: 9,
    comingSoon: false,
    externalUrl: process.env.NEXT_PUBLIC_APOLLO_GRAPHQL_URL,
    routes: [
      { slug: "basic-query", title: "Basic Query", order: 0, estimatedMinutes: 20, tags: ["fundamentals"] },
      { slug: "variables", title: "Variables", order: 1, estimatedMinutes: 20, tags: ["fundamentals"] },
      { slug: "lazy-query", title: "Lazy Query", order: 2, estimatedMinutes: 20, tags: ["client"] },
      { slug: "aliases", title: "Aliases", order: 3, estimatedMinutes: 15, tags: ["fundamentals"] },
      { slug: "fragments", title: "Fragments", order: 4, estimatedMinutes: 20, tags: ["fundamentals"] },
      { slug: "pagination", title: "Pagination", order: 5, estimatedMinutes: 25, tags: ["client", "data"] },
      { slug: "cursor-pagination", title: "Cursor Pagination", order: 6, estimatedMinutes: 25, tags: ["client", "data"] },
      { slug: "fetch-policies", title: "Fetch Policies", order: 7, estimatedMinutes: 25, tags: ["client", "cache"] },
      { slug: "cache-rw", title: "Cache Read & Write", order: 8, estimatedMinutes: 30, tags: ["cache"] },
      { slug: "use-mutation", title: "useMutation", order: 9, estimatedMinutes: 25, tags: ["client"] },
      { slug: "polling", title: "Polling", order: 10, estimatedMinutes: 20, tags: ["client", "realtime"] },
      { slug: "directives", title: "Directives", order: 11, estimatedMinutes: 20, tags: ["fundamentals"] },
      { slug: "introspection", title: "Introspection", order: 12, estimatedMinutes: 20, tags: ["advanced"] },
      { slug: "interfaces-unions", title: "Interfaces & Unions", order: 13, estimatedMinutes: 25, tags: ["schema"] },
      { slug: "custom-scalars", title: "Custom Scalars", order: 14, estimatedMinutes: 20, tags: ["schema"] },
      { slug: "cache-invalidation", title: "Cache Invalidation", order: 15, estimatedMinutes: 25, tags: ["cache"] },
      { slug: "optimistic-ui", title: "Optimistic UI", order: 16, estimatedMinutes: 25, tags: ["client", "ux"] },
      { slug: "reactive-vars", title: "Reactive Variables", order: 17, estimatedMinutes: 25, tags: ["client", "state"] },
      { slug: "type-policies", title: "Type Policies", order: 18, estimatedMinutes: 30, tags: ["cache", "advanced"] },
      { slug: "error-handling", title: "Error Handling", order: 19, estimatedMinutes: 25, tags: ["patterns"] },
      { slug: "link-chain", title: "Link Chain", order: 20, estimatedMinutes: 30, tags: ["client", "advanced"] },
      { slug: "use-fragment", title: "useFragment", order: 21, estimatedMinutes: 20, tags: ["client"] },
      { slug: "subscriptions", title: "Subscriptions", order: 22, estimatedMinutes: 30, tags: ["realtime"] },
      { slug: "testing", title: "Testing", order: 23, estimatedMinutes: 35, tags: ["testing"] },
      { slug: "suspense-query", title: "Suspense Query", order: 24, estimatedMinutes: 25, tags: ["client", "advanced"] },
      { slug: "background-query", title: "Background Query", order: 25, estimatedMinutes: 25, tags: ["client", "advanced"] },
      { slug: "loadable-query", title: "Loadable Query", order: 26, estimatedMinutes: 25, tags: ["client", "advanced"] },
      { slug: "defer", title: "Defer", order: 27, estimatedMinutes: 25, tags: ["advanced", "performance"] },
      { slug: "batch-http", title: "Batch HTTP", order: 28, estimatedMinutes: 20, tags: ["performance"] },
      { slug: "persisted-queries", title: "Persisted Queries", order: 29, estimatedMinutes: 20, tags: ["performance"] },
      { slug: "federation", title: "Federation", order: 30, estimatedMinutes: 40, tags: ["advanced", "federation"] },
      { slug: "file-uploads", title: "File Uploads", order: 31, estimatedMinutes: 20, tags: ["advanced"] },
    ],
    learningPath: [
      "basic-query", "variables", "lazy-query", "aliases",
      "fragments", "pagination", "cursor-pagination", "fetch-policies", "cache-rw",
      "use-mutation", "polling", "directives", "introspection", "interfaces-unions", "custom-scalars",
      "cache-invalidation", "optimistic-ui", "reactive-vars", "type-policies", "error-handling",
      "link-chain", "use-fragment", "subscriptions", "testing",
      "suspense-query", "background-query", "loadable-query", "defer",
      "batch-http", "persisted-queries", "federation", "file-uploads",
    ],
  },
  {
    slug: "web-fundamentals",
    title: "Web Fundamentals",
    description:
      "HTML, CSS, layout, responsive design, and accessibility — structured for frontend interview prep with lessons, code examples, and practice challenges.",
    version: "2.0.0",
    icon: "🌐",
    accentColor: "#0ea5e9",
    moduleCount: 10,
    totalHours: 14,
    comingSoon: false,
    routes: [
      { slug: "module/html-foundations", title: "HTML Foundations", order: 0, estimatedMinutes: 90, tags: ["html"] },
      { slug: "module/forms-accessibility", title: "Forms & Accessibility", order: 1, estimatedMinutes: 90, tags: ["forms", "a11y"] },
      { slug: "module/css-foundations", title: "CSS Foundations", order: 2, estimatedMinutes: 120, tags: ["css"] },
      { slug: "module/display-positioning", title: "Display & Positioning", order: 3, estimatedMinutes: 90, tags: ["css", "layout"] },
      { slug: "module/flexbox", title: "Flexbox", order: 4, estimatedMinutes: 120, tags: ["css", "layout"] },
      { slug: "module/css-grid", title: "CSS Grid", order: 5, estimatedMinutes: 120, tags: ["css", "layout"] },
      { slug: "module/responsive-design", title: "Responsive Design", order: 6, estimatedMinutes: 90, tags: ["css", "responsive"] },
      { slug: "module/visual-ui", title: "Visual UI Fundamentals", order: 7, estimatedMinutes: 90, tags: ["design", "css"] },
      { slug: "module/transitions-animations", title: "Transitions & Animations", order: 8, estimatedMinutes: 90, tags: ["css", "animation"] },
      { slug: "module/interview-challenges", title: "Interview Layout Challenges", order: 9, estimatedMinutes: 180, tags: ["interview", "challenges"] },
    ],
    learningPath: [
      "module/html-foundations",
      "module/forms-accessibility",
      "module/css-foundations",
      "module/display-positioning",
      "module/flexbox",
      "module/css-grid",
      "module/responsive-design",
      "module/visual-ui",
      "module/transitions-animations",
      "module/interview-challenges",
    ],
  },
  {
    slug: "graphql-core",
    title: "GraphQL Core",
    description:
      "Deep dive into the GraphQL specification — type system, execution model, introspection, and language internals.",
    version: "0.1.0",
    icon: "◈",
    accentColor: "#e10098",
    moduleCount: 8,
    totalHours: 6,
    comingSoon: true,
    routes: [],
    learningPath: [],
  },
  {
    slug: "react-deep-dive",
    title: "React Deep Dive",
    description:
      "Go beyond the API surface — understand how React actually works. Rendering, reconciliation, concurrent features, React 19, and the patterns that separate competent React developers from great ones.",
    version: "1.0.0",
    icon: "⚛️",
    accentColor: "#06b6d4",
    moduleCount: 10,
    totalHours: 5,
    comingSoon: false,
    routes: [
      { slug: "rendering-model", title: "The Rendering Model", order: 0, estimatedMinutes: 25, tags: ["react", "rendering"] },
      { slug: "use-state-use-reducer", title: "useState & useReducer", order: 1, estimatedMinutes: 25, tags: ["react", "hooks", "state"] },
      { slug: "use-effect-in-depth", title: "useEffect In Depth", order: 2, estimatedMinutes: 30, tags: ["react", "hooks", "effects"] },
      { slug: "use-ref-use-memo-use-callback", title: "useRef, useMemo & useCallback", order: 3, estimatedMinutes: 25, tags: ["react", "hooks", "performance"] },
      { slug: "context-in-depth", title: "Context In Depth", order: 4, estimatedMinutes: 25, tags: ["react", "context", "state"] },
      { slug: "custom-hooks", title: "Custom Hooks", order: 5, estimatedMinutes: 25, tags: ["react", "hooks", "patterns"] },
      { slug: "suspense-and-data-fetching", title: "Suspense & Data Fetching", order: 6, estimatedMinutes: 30, tags: ["react", "suspense"] },
      { slug: "concurrent-features", title: "Concurrent Features", order: 7, estimatedMinutes: 30, tags: ["react", "concurrent"] },
      { slug: "react-19", title: "React 19", order: 8, estimatedMinutes: 25, tags: ["react", "react-19"] },
      { slug: "component-patterns", title: "Component Patterns", order: 9, estimatedMinutes: 25, tags: ["react", "patterns"] },
    ],
    learningPath: [
      "rendering-model",
      "use-state-use-reducer",
      "use-effect-in-depth",
      "use-ref-use-memo-use-callback",
      "context-in-depth",
      "custom-hooks",
      "suspense-and-data-fetching",
      "concurrent-features",
      "react-19",
      "component-patterns",
    ],
  },
  {
    slug: "typescript-mastery",
    title: "TypeScript Mastery",
    description:
      "Go beyond the basics — structural typing, generics, utility types, mapped and conditional types, and the advanced patterns that separate TypeScript experts from beginners.",
    version: "1.0.0",
    icon: "🔷",
    accentColor: "#3b82f6",
    moduleCount: 8,
    totalHours: 4,
    comingSoon: false,
    routes: [
      { slug: "the-type-system", title: "The Type System", order: 0, estimatedMinutes: 20, tags: ["typescript", "fundamentals"] },
      { slug: "types-and-interfaces", title: "Types & Interfaces", order: 1, estimatedMinutes: 25, tags: ["typescript", "interfaces"] },
      { slug: "generics", title: "Generics", order: 2, estimatedMinutes: 30, tags: ["typescript", "generics"] },
      { slug: "utility-types", title: "Utility Types", order: 3, estimatedMinutes: 30, tags: ["typescript", "utility-types"] },
      { slug: "type-narrowing", title: "Type Narrowing", order: 4, estimatedMinutes: 25, tags: ["typescript", "narrowing"] },
      { slug: "mapped-types", title: "Mapped Types", order: 5, estimatedMinutes: 30, tags: ["typescript", "mapped-types"] },
      { slug: "conditional-types", title: "Conditional Types", order: 6, estimatedMinutes: 35, tags: ["typescript", "conditional-types"] },
      { slug: "advanced-patterns", title: "Advanced Patterns", order: 7, estimatedMinutes: 25, tags: ["typescript", "advanced"] },
    ],
    learningPath: [
      "the-type-system",
      "types-and-interfaces",
      "generics",
      "utility-types",
      "type-narrowing",
      "mapped-types",
      "conditional-types",
      "advanced-patterns",
    ],
  },
];
