import type { AcademyManifest, AcademyGroup, AcademyRoute } from "./types/academy";

export type MockAcademyRoute = Omit<AcademyRoute, "component">;

export interface MockAcademy extends Omit<
  AcademyManifest,
  "routes" | "totalEstimatedMinutes"
> {
  comingSoon?: boolean;
  externalUrl?: string;
  moduleCount: number;
  totalHours: number;
  routes: MockAcademyRoute[];
  groups?: AcademyGroup[];
}

export const MOCK_ACADEMIES: MockAcademy[] = [
  {
    slug: "apollo-graphql",
    title: "Apollo GraphQL",
    description:
      "Master the Apollo ecosystem — client, server, caching, federation, and production patterns for modern GraphQL APIs.",
    version: "1.0.0",
    icon: "⚡",
    accentColor: "#e535ab",
    moduleCount: 32,
    totalHours: 9,
    comingSoon: false,
    externalUrl: process.env.NEXT_PUBLIC_APOLLO_GRAPHQL_URL,
    routes: [
      {
        slug: "basic-query",
        title: "Basic Query",
        order: 0,
        estimatedMinutes: 20,
        tags: ["fundamentals"],
        keywords: ["useQuery", "gql", "query hook", "data fetching", "graphql query"],
      },
      {
        slug: "variables",
        title: "Variables",
        order: 1,
        estimatedMinutes: 20,
        tags: ["fundamentals"],
        keywords: ["query variables", "$variable", "dynamic queries", "variable types"],
      },
      {
        slug: "lazy-query",
        title: "Lazy Query",
        order: 2,
        estimatedMinutes: 20,
        tags: ["client"],
        keywords: ["useLazyQuery", "on-demand fetch", "lazy loading", "trigger query"],
      },
      {
        slug: "aliases",
        title: "Aliases",
        order: 4,
        estimatedMinutes: 15,
        tags: ["fundamentals"],
        keywords: ["field alias", "rename fields", "same field twice", "multiple queries"],
      },
      {
        slug: "fragments",
        title: "Fragments",
        order: 5,
        estimatedMinutes: 20,
        tags: ["fundamentals"],
        keywords: ["reusable fields", "fragment spread", "inline fragment", "...on"],
      },
      {
        slug: "pagination",
        title: "Pagination",
        order: 6,
        estimatedMinutes: 25,
        tags: ["client", "data"],
        keywords: ["offset pagination", "fetchMore", "load more", "page", "limit"],
      },
      {
        slug: "cursor-pagination",
        title: "Cursor Pagination",
        order: 7,
        estimatedMinutes: 25,
        tags: ["client", "data"],
        keywords: ["cursor", "relay", "connection", "edges", "nodes", "after", "before", "pageInfo"],
      },
      {
        slug: "fetch-policies",
        title: "Fetch Policies",
        order: 8,
        estimatedMinutes: 25,
        tags: ["client", "cache"],
        keywords: ["cache-first", "network-only", "no-cache", "cache-and-network", "standby", "fetchPolicy"],
      },
      {
        slug: "cache-rw",
        title: "Cache Read & Write",
        order: 9,
        estimatedMinutes: 30,
        tags: ["cache"],
        keywords: ["readQuery", "writeQuery", "readFragment", "writeFragment", "InMemoryCache", "cache update"],
      },
      {
        slug: "use-mutation",
        title: "useMutation",
        order: 10,
        estimatedMinutes: 25,
        tags: ["client"],
        keywords: ["mutation hook", "optimistic response", "update cache after mutation", "execute mutation"],
      },
      {
        slug: "polling",
        title: "Polling",
        order: 11,
        estimatedMinutes: 20,
        tags: ["client", "realtime"],
        keywords: ["startPolling", "stopPolling", "pollInterval", "live data", "auto-refresh"],
      },
      {
        slug: "directives",
        title: "Directives",
        order: 12,
        estimatedMinutes: 20,
        tags: ["fundamentals"],
        keywords: ["@skip", "@include", "@deprecated", "schema directives", "@client", "conditional field"],
      },
      {
        slug: "introspection",
        title: "Introspection",
        order: 13,
        estimatedMinutes: 20,
        tags: ["advanced"],
        keywords: ["__schema", "__type", "schema discovery", "schema explorer", "getIntrospectionQuery"],
      },
      {
        slug: "interfaces-unions",
        title: "Interfaces & Unions",
        order: 14,
        estimatedMinutes: 25,
        tags: ["schema"],
        keywords: ["abstract type", "__typename", "polymorphism", "union type", "interface type", "possibleTypes"],
      },
      {
        slug: "custom-scalars",
        title: "Custom Scalars",
        order: 15,
        estimatedMinutes: 20,
        tags: ["schema"],
        keywords: ["scalar type", "Date scalar", "JSON scalar", "serialize", "parseValue", "parseLiteral"],
      },
      {
        slug: "cache-invalidation",
        title: "Cache Invalidation",
        order: 16,
        estimatedMinutes: 25,
        tags: ["cache"],
        keywords: ["evict", "gc", "refetchQueries", "stale data", "cache.evict", "cache.gc", "cache reset"],
      },
      {
        slug: "optimistic-ui",
        title: "Optimistic UI",
        order: 16,
        estimatedMinutes: 25,
        tags: ["client", "ux"],
        keywords: ["optimisticResponse", "instant feedback", "rollback", "optimistic update"],
      },
      {
        slug: "reactive-vars",
        title: "Reactive Variables",
        order: 17,
        estimatedMinutes: 25,
        tags: ["client", "state"],
        keywords: ["makeVar", "local state", "reactive variable", "client-side state", "global state"],
      },
      {
        slug: "type-policies",
        title: "Type Policies",
        order: 18,
        estimatedMinutes: 30,
        tags: ["cache", "advanced"],
        keywords: ["keyFields", "merge function", "read function", "cache normalization", "custom key", "normalize"],
      },
      {
        slug: "error-handling",
        title: "Error Handling",
        order: 19,
        estimatedMinutes: 25,
        tags: ["patterns"],
        keywords: ["graphQLErrors", "networkError", "error link", "onError", "error boundary", "error policy"],
      },
      {
        slug: "link-chain",
        title: "Link Chain",
        order: 20,
        estimatedMinutes: 30,
        tags: ["client", "advanced"],
        keywords: ["ApolloLink", "auth link", "retry link", "from()", "concat()", "middleware chain"],
      },
      {
        slug: "use-fragment",
        title: "useFragment",
        order: 21,
        estimatedMinutes: 20,
        tags: ["client"],
        keywords: ["fragment watching", "partial data", "useFragment hook", "cache fragment"],
      },
      {
        slug: "subscriptions",
        title: "Subscriptions",
        order: 22,
        estimatedMinutes: 30,
        tags: ["realtime"],
        keywords: ["WebSocket", "useSubscription", "subscription link", "graphql-ws", "live updates", "ws"],
      },
      {
        slug: "testing",
        title: "Testing",
        order: 23,
        estimatedMinutes: 35,
        tags: ["testing"],
        keywords: ["MockedProvider", "mock queries", "unit testing", "jest", "vitest", "mock mutation"],
      },
      {
        slug: "suspense-query",
        title: "Suspense Query",
        order: 24,
        estimatedMinutes: 25,
        tags: ["client", "advanced"],
        keywords: ["useSuspenseQuery", "React Suspense", "streaming", "data loading"],
      },
      {
        slug: "background-query",
        title: "Background Query",
        order: 25,
        estimatedMinutes: 25,
        tags: ["client", "advanced"],
        keywords: ["useBackgroundQuery", "preload", "prefetch", "preloading data"],
      },
      {
        slug: "loadable-query",
        title: "Loadable Query",
        order: 26,
        estimatedMinutes: 25,
        tags: ["client", "advanced"],
        keywords: ["useLoadableQuery", "on-demand load", "deferred loading"],
      },
      {
        slug: "defer",
        title: "Defer",
        order: 27,
        estimatedMinutes: 25,
        tags: ["advanced", "performance"],
        keywords: ["@defer", "incremental delivery", "streaming", "partial results", "chunked response"],
      },
      {
        slug: "batch-http",
        title: "Batch HTTP",
        order: 28,
        estimatedMinutes: 20,
        tags: ["performance"],
        keywords: ["request batching", "BatchHttpLink", "reduce requests", "batch queries"],
      },
      {
        slug: "persisted-queries",
        title: "Persisted Queries",
        order: 29,
        estimatedMinutes: 20,
        tags: ["performance"],
        keywords: ["APQ", "automatic persisted queries", "hash", "GET requests", "bandwidth", "query hash"],
      },
      {
        slug: "federation",
        title: "Federation",
        order: 30,
        estimatedMinutes: 40,
        tags: ["advanced", "federation"],
        keywords: ["supergraph", "subgraph", "gateway", "@key", "distributed schema", "Apollo Router", "compose"],
      },
      {
        slug: "file-uploads",
        title: "File Uploads",
        order: 31,
        estimatedMinutes: 20,
        tags: ["advanced"],
        keywords: ["multipart", "Upload scalar", "FormData", "graphql-upload", "file upload mutation"],
      },
    ],
    learningPath: [
      "basic-query",
      "variables",
      "lazy-query",
      "aliases",
      "fragments",
      "pagination",
      "cursor-pagination",
      "fetch-policies",
      "cache-rw",
      "use-mutation",
      "polling",
      "directives",
      "introspection",
      "interfaces-unions",
      "custom-scalars",
      "cache-invalidation",
      "optimistic-ui",
      "reactive-vars",
      "type-policies",
      "error-handling",
      "link-chain",
      "use-fragment",
      "subscriptions",
      "testing",
      "suspense-query",
      "background-query",
      "loadable-query",
      "defer",
      "batch-http",
      "persisted-queries",
      "federation",
      "file-uploads",
    ],
  },
  {
    slug: "web-fundamentals",
    title: "Web Fundamentals",
    description:
      "HTML, CSS, layout, responsive design, and accessibility — structured for frontend interview prep with lessons, code examples, and practice challenges.",
    version: "2.0.0",
    icon: "🌐",
    accentColor: "#0ea5e9",
    moduleCount: 11,
    totalHours: 18,
    comingSoon: false,
    routes: [
      {
        slug: "module/html-foundations",
        title: "HTML Foundations",
        order: 0,
        estimatedMinutes: 90,
        tags: ["html"],
        keywords: ["semantic html", "elements", "attributes", "DOM", "doctype", "metadata", "heading", "section", "article", "nav", "main"],
      },
      {
        slug: "module/forms-accessibility",
        title: "Forms & Accessibility",
        order: 1,
        estimatedMinutes: 90,
        tags: ["forms", "a11y"],
        keywords: ["input", "label", "fieldset", "aria", "screen reader", "focus", "tab order", "keyboard navigation", "wcag", "role", "aria-label"],
      },
      {
        slug: "module/css-foundations",
        title: "CSS Foundations",
        order: 2,
        estimatedMinutes: 120,
        tags: ["css"],
        keywords: ["selectors", "specificity", "box model", "cascade", "inheritance", "custom properties", "css variables", "pseudo-class", "pseudo-element"],
      },
      {
        slug: "module/display-positioning",
        title: "Display & Positioning",
        order: 4,
        estimatedMinutes: 90,
        tags: ["css", "layout"],
        keywords: ["block", "inline", "inline-block", "position", "absolute", "relative", "fixed", "sticky", "z-index", "float", "overflow"],
      },
      {
        slug: "module/flexbox",
        title: "Flexbox",
        order: 5,
        estimatedMinutes: 120,
        tags: ["css", "layout"],
        keywords: ["flex container", "flex items", "justify-content", "align-items", "flex-wrap", "gap", "flex-direction", "order", "flex-grow", "flex-shrink", "align-self"],
      },
      {
        slug: "module/css-grid",
        title: "CSS Grid",
        order: 6,
        estimatedMinutes: 120,
        tags: ["css", "layout"],
        keywords: ["grid-template-columns", "grid-template-rows", "grid-area", "fr unit", "auto-fit", "auto-fill", "grid-gap", "place-items", "grid-column", "grid-row", "minmax"],
      },
      {
        slug: "module/responsive-design",
        title: "Responsive Design",
        order: 7,
        estimatedMinutes: 90,
        tags: ["css", "responsive"],
        keywords: ["media queries", "breakpoints", "mobile first", "viewport", "fluid layout", "rem", "em", "clamp", "min-width", "max-width", "container query"],
      },
      {
        slug: "module/visual-ui",
        title: "Visual UI Fundamentals",
        order: 8,
        estimatedMinutes: 90,
        tags: ["design", "css"],
        keywords: ["color", "typography", "box shadow", "gradients", "border-radius", "opacity", "filter", "transform", "visual design", "spacing", "font"],
      },
      {
        slug: "module/transitions-animations",
        title: "Transitions & Animations",
        order: 9,
        estimatedMinutes: 90,
        tags: ["css", "animation"],
        keywords: ["transition", "animation", "keyframes", "ease", "timing function", "transform", "cubic-bezier", "motion", "scale", "translate", "rotate"],
      },
      {
        slug: "module/interview-challenges",
        title: "Interview Layout Challenges",
        order: 10,
        estimatedMinutes: 180,
        tags: ["interview", "challenges"],
        keywords: ["layout challenge", "coding exercise", "frontend interview", "css challenge", "build layout", "navbar", "card grid"],
      },
      {
        slug: "module/layout-breakdown",
        title: "Layout Breakdown & Content Modeling",
        order: 11,
        estimatedMinutes: 240,
        tags: ["layout", "semantics", "interview"],
        keywords: ["design to code", "content modeling", "wireframe", "semantic structure", "component breakdown", "page structure"],
      },
    ],
    learningPath: [
      "module/html-foundations",
      "module/forms-accessibility",
      "module/css-foundations",
      "module/display-positioning",
      "module/flexbox",
      "module/css-grid",
      "module/responsive-design",
      "module/visual-ui",
      "module/transitions-animations",
      "module/interview-challenges",
      "module/layout-breakdown",
    ],
  },
  {
    slug: "graphql-core",
    title: "GraphQL Core",
    description:
      "Deep dive into the GraphQL specification — type system, execution model, introspection, and language internals.",
    version: "0.1.0",
    icon: "◈",
    accentColor: "#e10098",
    moduleCount: 8,
    totalHours: 6,
    comingSoon: true,
    routes: [],
    learningPath: [],
  },
  {
    slug: "react-deep-dive",
    title: "React Deep Dive",
    description:
      "Go beyond the API surface — understand how React actually works. Rendering, reconciliation, concurrent features, React 19, and the patterns that separate competent React developers from great ones.",
    version: "1.0.0",
    icon: "⚛️",
    accentColor: "#06b6d4",
    moduleCount: 11,
    totalHours: 6,
    comingSoon: false,
    routes: [
      {
        slug: "rendering-model",
        title: "The Rendering Model",
        order: 0,
        estimatedMinutes: 25,
        tags: ["react", "rendering"],
        keywords: ["reconciliation", "fiber", "virtual DOM", "diffing", "commit phase", "render phase", "re-render", "react tree"],
      },
      {
        slug: "use-state-use-reducer",
        title: "useState & useReducer",
        order: 1,
        estimatedMinutes: 25,
        tags: ["react", "hooks", "state"],
        keywords: ["state management", "state update", "dispatch", "action", "reducer", "batching", "setState", "state snapshot", "immutable update"],
      },
      {
        slug: "use-effect-in-depth",
        title: "useEffect In Depth",
        order: 2,
        estimatedMinutes: 30,
        tags: ["react", "hooks", "effects"],
        keywords: ["side effects", "cleanup", "dependency array", "useLayoutEffect", "lifecycle", "mount", "unmount", "synchronization", "effect dependencies"],
      },
      {
        slug: "use-ref-use-memo-use-callback",
        title: "useRef, useMemo & useCallback",
        order: 4,
        estimatedMinutes: 25,
        tags: ["react", "hooks", "performance"],
        keywords: ["memoization", "referential equality", "cache value", "skip re-render", "ref", "DOM ref", "persist value", "memo", "callback memoization"],
      },
      {
        slug: "context-in-depth",
        title: "Context In Depth",
        order: 5,
        estimatedMinutes: 25,
        tags: ["react", "context", "state"],
        keywords: ["prop drilling", "provider", "consumer", "global state", "context value", "re-render context", "useContext"],
      },
      {
        slug: "custom-hooks",
        title: "Custom Hooks",
        order: 6,
        estimatedMinutes: 25,
        tags: ["react", "hooks", "patterns"],
        keywords: ["extract logic", "reusable hooks", "custom hook", "useLocalStorage", "useFetch", "abstraction", "composable hooks"],
      },
      {
        slug: "suspense-and-data-fetching",
        title: "Suspense & Data Fetching",
        order: 7,
        estimatedMinutes: 30,
        tags: ["react", "suspense"],
        keywords: ["Suspense boundary", "React.lazy", "loading state", "data fetching", "streaming SSR", "use()", "fallback"],
      },
      {
        slug: "concurrent-features",
        title: "Concurrent Features",
        order: 8,
        estimatedMinutes: 30,
        tags: ["react", "concurrent"],
        keywords: ["useTransition", "startTransition", "useDeferredValue", "concurrent mode", "time slicing", "priority rendering", "interruptible rendering"],
      },
      {
        slug: "react-19",
        title: "React 19",
        order: 9,
        estimatedMinutes: 25,
        tags: ["react", "react-19"],
        keywords: ["actions", "useActionState", "useOptimistic", "use()", "Server Actions", "form actions", "asset loading", "new hooks"],
      },
      {
        slug: "component-patterns",
        title: "Component Patterns",
        order: 10,
        estimatedMinutes: 25,
        tags: ["react", "patterns"],
        keywords: ["compound components", "render props", "HOC", "higher order component", "controlled", "uncontrolled", "composition", "slots pattern"],
      },
      {
        slug: "interview-challenges",
        title: "Interview Challenges",
        order: 11,
        estimatedMinutes: 410,
        tags: ["react", "interviews", "challenge-bank", "forms", "tables", "performance"],
        keywords: ["coding challenge", "build component", "form validation", "infinite scroll", "frontend interview", "react problem", "data table"],
      },
    ],
    learningPath: [
      "rendering-model",
      "use-state-use-reducer",
      "use-effect-in-depth",
      "use-ref-use-memo-use-callback",
      "context-in-depth",
      "custom-hooks",
      "suspense-and-data-fetching",
      "concurrent-features",
      "react-19",
      "component-patterns",
      "interview-challenges",
    ],
    groups: [
      {
        id: "react-foundations",
        title: "Render & State Foundations",
        description: "The mental models behind rendering, state snapshots, effects, and memoization.",
        routeSlugs: [
          "rendering-model",
          "use-state-use-reducer",
          "use-effect-in-depth",
          "use-ref-use-memo-use-callback",
        ],
      },
      {
        id: "react-coordination",
        title: "Coordination & Modern React",
        description: "Sharing state, extracting logic, async boundaries, and modern concurrent React features.",
        routeSlugs: [
          "context-in-depth",
          "custom-hooks",
          "suspense-and-data-fetching",
          "concurrent-features",
          "react-19",
        ],
      },
      {
        id: "react-architecture-practice",
        title: "Architecture & Interview Practice",
        description: "Component API design and realistic React interview challenges.",
        routeSlugs: ["component-patterns", "interview-challenges"],
      },
    ],
  },
  {
    slug: "python-mastery",
    title: "Python Mastery",
    description:
      "Learn Python from fundamentals to advanced interview-ready topics. Designed for engineers coming from JavaScript/TypeScript — covering syntax, OOP, async, typing, testing, FastAPI, and coding interview patterns.",
    version: "1.0.0",
    icon: "🐍",
    accentColor: "#f59e0b",
    moduleCount: 25,
    totalHours: 15,
    comingSoon: false,
    routes: [
      { slug: "python-fundamentals", title: "Python Fundamentals", order: 0, estimatedMinutes: 30, tags: ["python", "fundamentals"], keywords: ["syntax", "variables", "print", "input", "indentation", "comments", "python basics", "PEP8", "string formatting"] },
      { slug: "data-types-and-collections", title: "Data Types and Collections", order: 1, estimatedMinutes: 35, tags: ["python", "data-types"], keywords: ["list", "dict", "tuple", "set", "string", "integer", "float", "boolean", "dictionary", "collection", "mutable", "immutable"] },
      { slug: "control-flow-and-loops", title: "Control Flow and Loops", order: 2, estimatedMinutes: 25, tags: ["python", "control-flow"], keywords: ["if", "elif", "else", "for loop", "while loop", "break", "continue", "range", "iteration", "pass"] },
      { slug: "functions-scope-and-arguments", title: "Functions, Scope, and Arguments", order: 4, estimatedMinutes: 30, tags: ["python", "functions"], keywords: ["def", "lambda", "*args", "**kwargs", "default args", "return", "closure", "scope", "LEGB", "first class function"] },
      { slug: "pythonic-code-and-comprehensions", title: "Pythonic Code and Comprehensions", order: 5, estimatedMinutes: 25, tags: ["python", "comprehensions"], keywords: ["list comprehension", "dict comprehension", "generator expression", "zip", "map", "filter", "enumerate", "walrus operator", ":="] },
      { slug: "object-oriented-python", title: "Object-Oriented Python", order: 6, estimatedMinutes: 40, tags: ["python", "oop"], keywords: ["class", "instance", "__init__", "self", "inheritance", "dunder", "magic methods", "dataclass", "__str__", "__repr__", "__eq__"] },
      { slug: "error-handling-and-debugging", title: "Error Handling and Debugging", order: 7, estimatedMinutes: 25, tags: ["python", "exceptions"], keywords: ["try", "except", "finally", "raise", "custom exception", "pdb", "traceback", "logging", "Exception", "ValueError"] },
      { slug: "modules-packages-and-envs", title: "Modules, Packages, and Environments", order: 8, estimatedMinutes: 25, tags: ["python", "modules"], keywords: ["import", "pip", "venv", "virtualenv", "requirements.txt", "__init__.py", "pyproject.toml", "poetry", "namespace"] },
      { slug: "file-io-and-standard-library", title: "File I/O and Standard Library", order: 9, estimatedMinutes: 30, tags: ["python", "stdlib"], keywords: ["open", "read", "write", "pathlib", "os", "sys", "json", "csv", "datetime", "collections", "itertools", "context manager"] },
      { slug: "advanced-python-concepts", title: "Advanced Python Concepts", order: 10, estimatedMinutes: 40, tags: ["python", "advanced"], keywords: ["decorators", "generators", "context managers", "metaclass", "descriptor", "__slots__", "__enter__", "__exit__", "yield", "@property", "functools"] },
      { slug: "modern-python-typing", title: "Modern Python Typing", order: 11, estimatedMinutes: 30, tags: ["python", "typing"], keywords: ["type hints", "Optional", "Union", "List", "Dict", "TypeVar", "Protocol", "TypedDict", "Generic", "Annotated", "mypy", "pyright"] },
      { slug: "testing-with-pytest", title: "Testing with Pytest", order: 12, estimatedMinutes: 30, tags: ["python", "testing"], keywords: ["pytest", "fixtures", "parametrize", "mock", "patch", "assert", "conftest", "test coverage", "monkeypatch", "capsys"] },
      { slug: "async-python", title: "Async Python", order: 13, estimatedMinutes: 35, tags: ["python", "async"], keywords: ["asyncio", "async def", "await", "event loop", "coroutine", "gather", "aiohttp", "async context manager", "asyncio.run", "TaskGroup"] },
      { slug: "backend-with-fastapi", title: "Backend with FastAPI", order: 14, estimatedMinutes: 40, tags: ["python", "fastapi"], keywords: ["FastAPI", "Pydantic", "route", "dependency injection", "OpenAPI", "Swagger", "request body", "response model", "APIRouter", "path params"] },
      { slug: "databases-and-orm-basics", title: "Databases and ORM Basics", order: 15, estimatedMinutes: 35, tags: ["python", "database"], keywords: ["SQLAlchemy", "ORM", "SQLite", "PostgreSQL", "query", "session", "model", "migration", "Alembic", "relationship"] },
      { slug: "algorithms-and-data-structures-python", title: "Algorithms and Data Structures in Python", order: 16, estimatedMinutes: 60, tags: ["python", "algorithms"], keywords: ["big O", "sorting", "binary search", "stack", "queue", "linked list", "tree", "graph", "hash map", "recursion", "dynamic programming"] },
      { slug: "python-interview-question-bank", title: "Python Interview Question Bank", order: 16, estimatedMinutes: 45, tags: ["python", "interviews"], keywords: ["interview questions", "GIL", "mutable vs immutable", "duck typing", "memory management", "CPython", "common python questions"] },
      { slug: "python-coding-challenges", title: "Python Coding Challenges", order: 17, estimatedMinutes: 60, tags: ["python", "challenges"], keywords: ["coding challenge", "leetcode", "hackerrank", "algorithm problem", "array manipulation", "string manipulation", "two pointers"] },
      { slug: "final-python-interview-project", title: "Final Python Interview Project", order: 18, estimatedMinutes: 45, tags: ["python", "project"], keywords: ["capstone", "portfolio project", "REST API", "end-to-end", "production Python", "build api"] },
      { slug: "python-glossary-and-cheat-sheet", title: "Python Glossary and Cheat Sheet", order: 19, estimatedMinutes: 20, tags: ["python", "reference"], keywords: ["reference", "cheatsheet", "quick reference", "syntax guide", "glossary", "cheat sheet"] },
      { slug: "python-for-js-ts-developers", title: "Python for JS/TS Developers", order: 20, estimatedMinutes: 30, tags: ["python", "javascript"], keywords: ["JavaScript to Python", "TypeScript comparison", "migration", "null vs None", "let var const", "async comparison", "JS vs Python"] },
      { slug: "python-frameworks-and-architecture", title: "Python Web Frameworks and Architecture", order: 21, estimatedMinutes: 50, tags: ["python", "django", "fastapi", "architecture"], keywords: ["Django", "Flask", "FastAPI comparison", "MVC", "WSGI", "ASGI", "framework choice", "web framework"] },
      { slug: "python-concurrency", title: "Python Concurrency", order: 22, estimatedMinutes: 40, tags: ["python", "concurrency", "threading", "gil"], keywords: ["threading", "multiprocessing", "GIL", "concurrent.futures", "thread safety", "race condition", "asyncio vs threading", "parallel"] },
      { slug: "python-design-patterns", title: "Python Design Patterns", order: 23, estimatedMinutes: 45, tags: ["python", "design-patterns", "oop"], keywords: ["singleton", "factory", "observer", "strategy", "decorator pattern", "dependency injection", "SOLID", "clean code"] },
      { slug: "python-security", title: "Security in Python APIs", order: 24, estimatedMinutes: 40, tags: ["python", "security", "jwt", "fastapi"], keywords: ["JWT", "OAuth2", "password hashing", "bcrypt", "SQL injection", "CORS", "authentication", "authorization", "secrets"] },
    ],
    learningPath: [
      "python-fundamentals",
      "data-types-and-collections",
      "control-flow-and-loops",
      "functions-scope-and-arguments",
      "pythonic-code-and-comprehensions",
      "object-oriented-python",
      "error-handling-and-debugging",
      "modules-packages-and-envs",
      "file-io-and-standard-library",
      "advanced-python-concepts",
      "modern-python-typing",
      "testing-with-pytest",
      "async-python",
      "backend-with-fastapi",
      "databases-and-orm-basics",
      "algorithms-and-data-structures-python",
      "python-interview-question-bank",
      "python-coding-challenges",
      "final-python-interview-project",
      "python-glossary-and-cheat-sheet",
      "python-for-js-ts-developers",
      "python-frameworks-and-architecture",
      "python-concurrency",
      "python-design-patterns",
      "python-security",
    ],
    groups: [
      {
        id: "python-foundations",
        title: "Python Foundations",
        description: "Syntax, data modeling, control flow, modules, and standard-library fluency.",
        routeSlugs: [
          "python-fundamentals",
          "data-types-and-collections",
          "control-flow-and-loops",
          "functions-scope-and-arguments",
          "pythonic-code-and-comprehensions",
          "object-oriented-python",
          "error-handling-and-debugging",
          "modules-packages-and-envs",
          "file-io-and-standard-library",
        ],
      },
      {
        id: "advanced-python-tooling",
        title: "Advanced Language & Tooling",
        description: "Modern Python features, typing, testing, and async mental models.",
        routeSlugs: [
          "advanced-python-concepts",
          "modern-python-typing",
          "testing-with-pytest",
          "async-python",
        ],
      },
      {
        id: "python-backend-foundations",
        title: "Backend & Data Foundations",
        description: "Building APIs and working with persistence layers in production-style Python systems.",
        routeSlugs: ["backend-with-fastapi", "databases-and-orm-basics"],
      },
      {
        id: "python-interview-practice",
        title: "Interview Prep & Applied Practice",
        description: "Algorithms, interview reps, coding drills, portfolio projects, and quick-reference review.",
        routeSlugs: [
          "algorithms-and-data-structures-python",
          "python-interview-question-bank",
          "python-coding-challenges",
          "final-python-interview-project",
          "python-glossary-and-cheat-sheet",
          "python-for-js-ts-developers",
        ],
      },
      {
        id: "production-python-architecture",
        title: "Production Python Architecture",
        description: "Framework choices, concurrency, design patterns, and API security for senior-level backend work.",
        routeSlugs: [
          "python-frameworks-and-architecture",
          "python-concurrency",
          "python-design-patterns",
          "python-security",
        ],
      },
    ],
  },
  {
    slug: "typescript-mastery",
    title: "TypeScript Mastery",
    description:
      "Go beyond the basics — structural typing, generics, utility types, mapped and conditional types, and the advanced patterns that separate TypeScript experts from beginners.",
    version: "1.0.0",
    icon: "🔷",
    accentColor: "#3b82f6",
    moduleCount: 8,
    totalHours: 4,
    comingSoon: false,
    routes: [
      {
        slug: "the-type-system",
        title: "The Type System",
        order: 0,
        estimatedMinutes: 20,
        tags: ["typescript", "fundamentals"],
        keywords: ["structural typing", "type inference", "any", "unknown", "never", "void", "type checking", "duck typing", "nominal typing"],
      },
      {
        slug: "types-and-interfaces",
        title: "Types & Interfaces",
        order: 1,
        estimatedMinutes: 25,
        tags: ["typescript", "interfaces"],
        keywords: ["interface vs type", "extends", "intersection", "union", "literal type", "readonly", "optional property", "index signature", "type alias"],
      },
      {
        slug: "generics",
        title: "Generics",
        order: 2,
        estimatedMinutes: 30,
        tags: ["typescript", "generics"],
        keywords: ["generic function", "generic class", "constraints", "extends constraint", "keyof", "typeof", "default generic", "T", "type parameter"],
      },
      {
        slug: "utility-types",
        title: "Utility Types",
        order: 4,
        estimatedMinutes: 30,
        tags: ["typescript", "utility-types"],
        keywords: ["Partial", "Required", "Pick", "Omit", "Record", "Exclude", "Extract", "ReturnType", "Parameters", "NonNullable", "Awaited"],
      },
      {
        slug: "type-narrowing",
        title: "Type Narrowing",
        order: 5,
        estimatedMinutes: 25,
        tags: ["typescript", "narrowing"],
        keywords: ["typeof guard", "instanceof", "in operator", "discriminated union", "type predicate", "is keyword", "assertion functions", "type guard"],
      },
      {
        slug: "mapped-types",
        title: "Mapped Types",
        order: 6,
        estimatedMinutes: 30,
        tags: ["typescript", "mapped-types"],
        keywords: ["keyof", "in keyof", "as clause", "remapping", "template literal types", "Readonly mapped", "Nullable mapped", "key remapping"],
      },
      {
        slug: "conditional-types",
        title: "Conditional Types",
        order: 7,
        estimatedMinutes: 35,
        tags: ["typescript", "conditional-types"],
        keywords: ["extends ternary", "infer", "distributive", "UnwrapPromise", "DeepPartial", "recursive types", "conditional inference"],
      },
      {
        slug: "advanced-patterns",
        title: "Advanced Patterns",
        order: 8,
        estimatedMinutes: 25,
        tags: ["typescript", "advanced"],
        keywords: ["template literal types", "satisfies", "const assertion", "overloads", "declaration merging", "module augmentation", "branded types", "opaque types"],
      },
    ],
    learningPath: [
      "the-type-system",
      "types-and-interfaces",
      "generics",
      "utility-types",
      "type-narrowing",
      "mapped-types",
      "conditional-types",
      "advanced-patterns",
    ],
    groups: [
      {
        id: "typescript-foundations",
        title: "Type Foundations",
        description: "The core mental model behind TypeScript's structural type system.",
        routeSlugs: ["the-type-system", "types-and-interfaces"],
      },
      {
        id: "type-construction",
        title: "Reusable Type Construction",
        description: "Building stronger reusable abstractions with generics, utility types, narrowing, and mapped types.",
        routeSlugs: ["generics", "utility-types", "type-narrowing", "mapped-types"],
      },
      {
        id: "advanced-inference-patterns",
        title: "Advanced Inference & Patterns",
        description: "Conditional typing, inference, and advanced design patterns for large codebases.",
        routeSlugs: ["conditional-types", "advanced-patterns"],
      },
    ],
  },
  {
    slug: "nodejs-mastery",
    title: "Node.js Mastery",
    description:
      "Master Node.js from runtime internals to production architecture. Learn the event loop, async patterns, streams, networking, observability, performance, security, and interview-ready backend scenarios.",
    version: "1.0.0",
    icon: "🟢",
    accentColor: "#22c55e",
    moduleCount: 10,
    totalHours: 7,
    comingSoon: false,
    routes: [
      { slug: "node-runtime-architecture", title: "Node.js Runtime Architecture", order: 0, estimatedMinutes: 35, tags: ["node", "runtime", "v8", "libuv"], keywords: ["V8 engine", "libuv", "C++ bindings", "heap", "garbage collection", "single threaded", "non-blocking", "internals"] },
      { slug: "event-loop-and-async-patterns", title: "Event Loop & Async Patterns", order: 1, estimatedMinutes: 45, tags: ["node", "event-loop", "async", "promises"], keywords: ["call stack", "task queue", "microtask queue", "setTimeout", "setImmediate", "process.nextTick", "phases", "callback hell", "async await", "Promise chaining"] },
      { slug: "modules-packages-and-tooling", title: "Modules, Packages & Tooling", order: 2, estimatedMinutes: 40, tags: ["node", "esm", "commonjs", "npm"], keywords: ["require", "module.exports", "import export", "ESM", "CommonJS", "package.json", "node_modules", "npm", "yarn", "pnpm", "cjs vs esm"] },
      { slug: "buffers-streams-and-files", title: "Buffers, Streams & File Systems", order: 4, estimatedMinutes: 45, tags: ["node", "buffers", "streams", "fs"], keywords: ["Buffer", "Readable stream", "Writable stream", "Transform stream", "pipe", "readline", "fs.readFile", "fs.createReadStream", "backpressure", "binary data"] },
      { slug: "networking-http-and-apis", title: "Networking, HTTP & APIs", order: 5, estimatedMinutes: 45, tags: ["node", "http", "fetch", "apis"], keywords: ["http.createServer", "IncomingMessage", "ServerResponse", "fetch", "https", "TCP", "socket", "REST", "JSON API", "headers", "status codes"] },
      { slug: "testing-debugging-and-observability", title: "Testing, Debugging & Observability", order: 6, estimatedMinutes: 40, tags: ["node", "testing", "debugging", "observability"], keywords: ["vitest", "jest", "node --inspect", "debugger", "pino", "winston", "OpenTelemetry", "metrics", "structured logging", "traces"] },
      { slug: "performance-workers-and-scaling", title: "Performance, Workers & Scaling", order: 7, estimatedMinutes: 45, tags: ["node", "performance", "worker-threads", "scaling"], keywords: ["worker_threads", "cluster", "child_process", "CPU bound", "spawn", "fork", "PM2", "memory leak", "profiling", "flame graph", "throughput"] },
      { slug: "security-and-production-hardening", title: "Security & Production Hardening", order: 8, estimatedMinutes: 40, tags: ["node", "security", "production", "secrets"], keywords: ["helmet", "rate limiting", "env vars", "secrets", "HTTPS", "SSRF", "injection", "input validation", "CORS", "hardening"] },
      { slug: "node-architecture-patterns", title: "Node.js Architecture Patterns", order: 9, estimatedMinutes: 40, tags: ["node", "architecture", "queues", "services"], keywords: ["microservices", "event emitter", "pub-sub", "queue", "BullMQ", "CQRS", "service layer", "repository pattern", "domain events"] },
      { slug: "nodejs-most-common-interview-questions", title: "Node.js Most Common Interview Questions", order: 10, estimatedMinutes: 60, tags: ["node", "interview", "questions", "backend"], keywords: ["event loop question", "callback vs promise", "streams vs buffers", "cluster vs worker threads", "memory management", "Node.js internals interview", "common node questions"] },
    ],
    learningPath: [
      "node-runtime-architecture",
      "event-loop-and-async-patterns",
      "modules-packages-and-tooling",
      "buffers-streams-and-files",
      "networking-http-and-apis",
      "testing-debugging-and-observability",
      "performance-workers-and-scaling",
      "security-and-production-hardening",
      "node-architecture-patterns",
      "nodejs-most-common-interview-questions",
    ],
    groups: [
      {
        id: "node-foundations",
        title: "Runtime Foundations",
        description: "How Node.js actually runs JavaScript: V8, libuv, the event loop, packages, and async control flow.",
        routeSlugs: [
          "node-runtime-architecture",
          "event-loop-and-async-patterns",
          "modules-packages-and-tooling",
        ],
      },
      {
        id: "io-networking",
        title: "I/O, Data Flow & Networking",
        description: "Buffers, streams, files, sockets, HTTP servers, and modern API-building primitives.",
        routeSlugs: [
          "buffers-streams-and-files",
          "networking-http-and-apis",
        ],
      },
      {
        id: "engineering-production",
        title: "Engineering for Production",
        description: "Testing, observability, performance tuning, worker strategies, security, and production readiness.",
        routeSlugs: [
          "testing-debugging-and-observability",
          "performance-workers-and-scaling",
          "security-and-production-hardening",
        ],
      },
      {
        id: "architecture-interview",
        title: "Architecture & Interview Prep",
        description: "Service boundaries, queues, background jobs, and the interview answers senior Node.js engineers are expected to know.",
        routeSlugs: [
          "node-architecture-patterns",
          "nodejs-most-common-interview-questions",
        ],
      },
    ],
  },
  {
    slug: "express-backend",
    title: "Express.js & Backend Engineering",
    description:
      "Master Express.js from fundamentals to production — REST design, authentication, authorization, caching, security, testing, and performance patterns for Node.js backends.",
    version: "1.0.0",
    icon: "🚀",
    accentColor: "#10b981",
    moduleCount: 23,
    totalHours: 14,
    comingSoon: false,
    routes: [
      { slug: "express-fundamentals", title: "Express Fundamentals", order: 0, estimatedMinutes: 30, tags: ["express", "fundamentals", "routing"], keywords: ["app.get", "app.post", "router", "route handler", "request", "response", "next", "app.use", "listen", "port"] },
      { slug: "middleware-pipeline", title: "Middleware & the Request Pipeline", order: 1, estimatedMinutes: 35, tags: ["express", "middleware", "pipeline"], keywords: ["req", "res", "next()", "error middleware", "custom middleware", "router.use", "order of middleware", "body parser", "morgan"] },
      { slug: "rest-api-design", title: "REST API Design", order: 2, estimatedMinutes: 35, tags: ["rest", "api-design", "http"], keywords: ["HTTP methods", "status codes", "resource naming", "versioning", "HATEOAS", "idempotent", "PUT vs PATCH", "200 201 204 400 401 403 404 422 500"] },
      { slug: "validation-error-handling", title: "Validation & Error Handling", order: 4, estimatedMinutes: 35, tags: ["validation", "zod", "error-handling"], keywords: ["zod schema", "express-validator", "input validation", "400 Bad Request", "error middleware", "centralized error handling", "joi"] },
      { slug: "authentication-jwt", title: "Authentication with JWT", order: 5, estimatedMinutes: 40, tags: ["auth", "jwt", "security"], keywords: ["JSON Web Token", "sign", "verify", "Bearer token", "access token", "refresh token", "secret key", "jsonwebtoken", "passport"] },
      { slug: "authentication-sessions", title: "Authentication with Sessions & Cookies", order: 6, estimatedMinutes: 35, tags: ["auth", "sessions", "cookies", "csrf"], keywords: ["express-session", "cookie-session", "session store", "HttpOnly", "Secure", "SameSite", "CSRF token", "logout", "session fixation"] },
      { slug: "authorization-rbac", title: "Authorization: RBAC & Permissions", order: 7, estimatedMinutes: 35, tags: ["authorization", "rbac", "abac", "permissions"], keywords: ["role-based", "permission", "middleware guard", "policy", "admin", "resource owner", "ABAC", "can user"] },
      { slug: "database-integration", title: "Database Integration", order: 8, estimatedMinutes: 40, tags: ["database", "prisma", "postgresql", "orm"], keywords: ["Prisma Client", "raw query", "transaction", "connection pool", "N+1 problem", "eager loading", "query builder", "migration"] },
      { slug: "caching-redis", title: "Caching with Redis", order: 9, estimatedMinutes: 35, tags: ["redis", "caching", "performance"], keywords: ["cache-aside", "TTL", "Redis client", "ioredis", "cache invalidation", "ETag", "Cache-Control", "memoize", "in-memory cache"] },
      { slug: "security-best-practices", title: "Security Best Practices", order: 10, estimatedMinutes: 40, tags: ["security", "helmet", "cors", "owasp"], keywords: ["XSS", "CSRF", "SQL injection", "OWASP Top 10", "cors", "rate limiter", "input sanitization", "bcrypt", "password hashing", "hpp"] },
      { slug: "testing-express", title: "Testing Express APIs", order: 11, estimatedMinutes: 35, tags: ["testing", "supertest", "vitest", "integration-tests"], keywords: ["supertest", "integration test", "test database", "mock", "beforeAll", "afterAll", "HTTP test", "API test", "status assertion", "test setup"] },
      { slug: "production-ready", title: "Production-Ready Express", order: 12, estimatedMinutes: 40, tags: ["production", "performance", "monitoring", "pm2"], keywords: ["graceful shutdown", "clustering", "PM2", "structured logging", "health check", "load balancer", "zero downtime", "process management"] },
      { slug: "interview-prep", title: "Interview Questions & Code Challenges", order: 13, estimatedMinutes: 60, tags: ["interview", "questions", "code-challenges", "prep"], keywords: ["backend interview", "express interview", "node interview", "API design", "code challenge", "system design lite"] },
      { slug: "interview-01-node-fundamentals", title: "Interview: Node.js Fundamentals", order: 14, estimatedMinutes: 30, tags: ["interview", "node", "fundamentals"], keywords: ["V8", "runtime", "non-blocking", "single thread", "event driven", "Node.js basics interview"] },
      { slug: "interview-02-event-loop", title: "Interview: Event Loop & Async Behavior", order: 15, estimatedMinutes: 35, tags: ["interview", "event-loop", "async"], keywords: ["phases", "call stack", "microtask", "macrotask", "tick", "queue order", "event loop interview"] },
      { slug: "interview-03-promises-async", title: "Interview: Promises, Async/Await & Error Handling", order: 16, estimatedMinutes: 35, tags: ["interview", "promises", "async-await"], keywords: ["Promise.all", "Promise.race", "async function", "error handling async", "chaining", "unhandled rejection"] },
      { slug: "interview-04-express-fundamentals", title: "Interview: Express.js Fundamentals", order: 16, estimatedMinutes: 40, tags: ["interview", "express", "middleware"], keywords: ["middleware order", "error handler", "route params", "query string", "body parser", "express interview questions"] },
      { slug: "interview-05-rest-api-design", title: "Interview: REST API Design", order: 17, estimatedMinutes: 40, tags: ["interview", "rest", "http"], keywords: ["REST principles", "stateless", "resource", "idempotency", "status code interview", "HTTP verbs"] },
      { slug: "interview-06-auth", title: "Interview: Authentication & Authorization", order: 18, estimatedMinutes: 45, tags: ["interview", "jwt", "sessions", "oauth"], keywords: ["token storage", "refresh token", "OAuth 2.0", "OpenID Connect", "2FA", "auth interview"] },
      { slug: "interview-07-security", title: "Interview: Security", order: 19, estimatedMinutes: 40, tags: ["interview", "security", "owasp", "xss"], keywords: ["injection attack", "OWASP", "XSS prevention", "CORS origin", "security interview", "penetration testing basics"] },
      { slug: "interview-08-databases", title: "Interview: Databases & Data Access", order: 20, estimatedMinutes: 45, tags: ["interview", "database", "orm", "prisma"], keywords: ["query optimization", "index", "transaction isolation", "ACID", "N+1", "connection pool interview", "database interview"] },
      { slug: "interview-09-architecture", title: "Interview: Architecture & Clean Code", order: 21, estimatedMinutes: 45, tags: ["interview", "architecture", "clean-code"], keywords: ["SOLID principles", "separation of concerns", "DRY", "dependency injection", "service layer", "hexagonal architecture", "architecture interview"] },
      { slug: "interview-10-testing", title: "Interview: Testing", order: 22, estimatedMinutes: 45, tags: ["interview", "testing", "vitest", "supertest"], keywords: ["test pyramid", "unit vs integration vs e2e", "mocking strategy", "test coverage", "TDD", "testing interview"] },
    ],
    learningPath: [
      "express-fundamentals",

      "middleware-pipeline",
      "rest-api-design",
      "validation-error-handling",
      "authentication-jwt",
      "authentication-sessions",
      "authorization-rbac",
      "database-integration",
      "caching-redis",
      "security-best-practices",
      "testing-express",
      "production-ready",
      "interview-prep",
      "interview-01-node-fundamentals",
      "interview-02-event-loop",
      "interview-03-promises-async",
      "interview-04-express-fundamentals",
      "interview-05-rest-api-design",
      "interview-06-auth",
      "interview-07-security",
      "interview-08-databases",
      "interview-09-architecture",
      "interview-10-testing",
    ],
    groups: [
      {
        id: "express-core",
        title: "Express Core",
        description: "The fundamental building blocks: routing, middleware, REST design, and robust error handling.",
        routeSlugs: [
          "express-fundamentals",
          "middleware-pipeline",
          "rest-api-design",
          "validation-error-handling",
        ],
      },
      {
        id: "auth-authorization",
        title: "Authentication & Authorization",
        description: "JWT, session-based auth, CSRF, RBAC, ABAC, and composable permission middleware.",
        routeSlugs: [
          "authentication-jwt",
          "authentication-sessions",
          "authorization-rbac",
        ],
      },
      {
        id: "data-caching",
        title: "Data & Caching",
        description: "Database integration patterns, Prisma, the N+1 problem, Redis caching strategies, and HTTP cache headers.",
        routeSlugs: [
          "database-integration",
          "caching-redis",
        ],
      },
      {
        id: "production-engineering",
        title: "Production Engineering",
        description: "Security hardening, integration testing with supertest, clustering, graceful shutdown, structured logging, and monitoring.",
        routeSlugs: [
          "security-best-practices",
          "testing-express",
          "production-ready",
        ],
      },
      {
        id: "interview-prep",
        title: "Interview Prep",
        description: "All theory questions an interviewer will ask — 18 sections covering every topic senior engineers are tested on.",
        routeSlugs: [
          "interview-prep",
          "interview-01-node-fundamentals",
          "interview-02-event-loop",
          "interview-03-promises-async",
          "interview-04-express-fundamentals",
          "interview-05-rest-api-design",
          "interview-06-auth",
          "interview-07-security",
          "interview-08-databases",
          "interview-09-architecture",
          "interview-10-testing",
        ],
      },
    ],
  },
  {
    slug: "nextjs-mastery",
    title: "Next.js Mastery",
    description:
      "Master Next.js App Router from routing fundamentals to production deployment. Server Components, data fetching, caching, Server Actions, middleware, auth patterns, and the interview answers senior engineers are expected to know.",
    version: "1.0.0",
    icon: "▲",
    accentColor: "#171717",
    moduleCount: 16,
    totalHours: 11,
    comingSoon: false,
    routes: [
      {
        slug: "app-router-fundamentals",
        title: "App Router Fundamentals",
        order: 0,
        estimatedMinutes: 40,
        tags: ["nextjs", "routing", "layouts"],
        keywords: ["file-based routing", "layout.tsx", "page.tsx", "loading.tsx", "error.tsx", "route groups", "nested layouts", "template.tsx", "not-found.tsx"],
      },
      {
        slug: "server-components-vs-client-components",
        title: "Server Components vs Client Components",
        order: 1,
        estimatedMinutes: 45,
        tags: ["nextjs", "rsc", "components"],
        keywords: ["react server components", "use client", "client boundary", "server component", "hydration", "serializable props", "composition patterns", "RSC mental model"],
      },
      {
        slug: "routing-advanced",
        title: "Advanced Routing",
        order: 2,
        estimatedMinutes: 40,
        tags: ["nextjs", "routing", "middleware"],
        keywords: ["dynamic routes", "catch-all", "parallel routes", "intercepting routes", "route handlers", "middleware.ts", "params Promise", "edge runtime", "@slot"],
      },
      {
        slug: "data-fetching-and-caching",
        title: "Data Fetching & Caching",
        order: 4,
        estimatedMinutes: 50,
        tags: ["nextjs", "caching", "data-fetching"],
        keywords: ["fetch cache", "next.revalidate", "no-store", "ISR", "generateStaticParams", "unstable_cache", "request memoization", "Data Cache", "Full Route Cache", "Router Cache", "revalidateTag", "revalidatePath"],
      },
      {
        slug: "server-actions",
        title: "Server Actions",
        order: 5,
        estimatedMinutes: 40,
        tags: ["nextjs", "server-actions", "mutations"],
        keywords: ["use server", "form actions", "progressive enhancement", "useActionState", "useFormState", "useFormStatus", "useOptimistic", "revalidation", "Server Action security"],
      },
      {
        slug: "nextjs-performance-and-optimization",
        title: "Performance & Optimization",
        order: 6,
        estimatedMinutes: 40,
        tags: ["nextjs", "performance", "optimization"],
        keywords: ["next/image", "next/font", "next/script", "Suspense streaming", "Partial Prerendering", "PPR", "dynamic imports", "bundle analysis", "prefetching", "sizes prop"],
      },
      {
        slug: "metadata-and-seo",
        title: "Metadata & SEO",
        order: 7,
        estimatedMinutes: 25,
        tags: ["nextjs", "seo", "metadata"],
        keywords: ["metadata export", "generateMetadata", "Open Graph", "Twitter cards", "robots.ts", "sitemap.ts", "opengraph-image", "canonical URL", "metadata inheritance"],
      },
      {
        slug: "authentication-and-middleware",
        title: "Authentication & Middleware",
        order: 8,
        estimatedMinutes: 45,
        tags: ["nextjs", "auth", "middleware", "security"],
        keywords: ["Auth.js", "NextAuth", "JWT", "database sessions", "middleware auth", "next/headers", "cookies", "edge runtime constraints", "RBAC", "session strategy", "jose"],
      },
      {
        slug: "deployment-and-edge",
        title: "Deployment & Edge",
        order: 9,
        estimatedMinutes: 35,
        tags: ["nextjs", "deployment", "edge", "vercel"],
        keywords: ["Vercel deployment", "Edge Runtime", "Node.js runtime", "environment variables", "NEXT_PUBLIC", "next.config.ts", "ISR deployment", "standalone output", "static export", "Docker"],
      },
      {
        slug: "pages-router-and-migration",
        title: "Pages Router & Migration to App Router",
        order: 10,
        estimatedMinutes: 50,
        tags: ["nextjs", "pages-router", "migration", "ssr", "ssg"],
        keywords: ["getServerSideProps", "getStaticProps", "getStaticPaths", "ISR", "Pages Router", "_app.tsx", "_document.tsx", "useRouter next/router", "fallback blocking", "incremental migration", "coexistence"],
      },
      {
        slug: "route-segment-config",
        title: "Route Segment Config",
        order: 11,
        estimatedMinutes: 35,
        tags: ["nextjs", "rendering", "caching", "config"],
        keywords: ["dynamic segment config", "force-dynamic", "force-static", "revalidate", "runtime edge", "fetchCache", "generateStaticParams", "segment config vs fetch"],
      },
      {
        slug: "navigation-hooks",
        title: "Navigation Hooks & App Router Navigation",
        order: 12,
        estimatedMinutes: 30,
        tags: ["nextjs", "navigation", "hooks", "app-router"],
        keywords: ["useRouter App Router", "usePathname", "useSearchParams", "useParams", "useSelectedLayoutSegment", "next/navigation", "next/router vs next/navigation", "router.refresh"],
      },
      {
        slug: "testing-nextjs",
        title: "Testing Next.js Applications",
        order: 13,
        estimatedMinutes: 45,
        tags: ["nextjs", "testing", "vitest", "jest", "server-components"],
        keywords: ["test Route Handler", "mock next/navigation", "test Server Action", "test Server Component", "test middleware", "Playwright Next.js", "vi.mock next/navigation", "renderToString server component"],
      },
      {
        slug: "internationalization",
        title: "Internationalization (i18n)",
        order: 14,
        estimatedMinutes: 35,
        tags: ["nextjs", "i18n", "localization", "middleware"],
        keywords: ["i18n App Router", "next-intl", "lang segment", "[lang] dynamic segment", "locale detection middleware", "Accept-Language", "hreflang", "generateStaticParams locales", "sub-path routing"],
      },
      {
        slug: "nextjs-15-and-observability",
        title: "Next.js 15 APIs & Observability",
        order: 15,
        estimatedMinutes: 35,
        tags: ["nextjs", "nextjs-15", "observability", "instrumentation", "after"],
        keywords: ["after() API", "params Promise", "caching defaults Next.js 15", "forbidden unauthorized", "instrumentation.ts", "onRequestError", "Turbopack stable", "connection() API", "Next.js 15 breaking changes"],
      },
      {
        slug: "nextjs-interview-questions",
        title: "Next.js Interview Questions",
        order: 16,
        estimatedMinutes: 60,
        tags: ["nextjs", "interview", "questions"],
        keywords: ["RSC interview", "caching interview", "hydration error", "params Promise Next.js 15", "Pages Router vs App Router", "Server Actions interview", "ISR vs SSR vs SSG vs CSR", "useActionState", "PPR interview"],
      },
    ],
    learningPath: [
      "app-router-fundamentals",
      "server-components-vs-client-components",
      "routing-advanced",
      "data-fetching-and-caching",
      "server-actions",
      "nextjs-performance-and-optimization",
      "metadata-and-seo",
      "authentication-and-middleware",
      "deployment-and-edge",
      "pages-router-and-migration",
      "route-segment-config",
      "navigation-hooks",
      "testing-nextjs",
      "internationalization",
      "nextjs-15-and-observability",
      "nextjs-interview-questions",
    ],
    groups: [
      {
        id: "app-router-foundations",
        title: "App Router Foundations",
        description:
          "File-based routing, the Server/Client Component split, and advanced routing patterns: parallel routes, intercepting routes, middleware, and route handlers.",
        routeSlugs: [
          "app-router-fundamentals",
          "server-components-vs-client-components",
          "routing-advanced",
        ],
      },
      {
        id: "data-and-caching",
        title: "Data & Caching",
        description:
          "The 4-layer cache model, fetch options, ISR, revalidation strategies, and Server Actions for mutations with React integration.",
        routeSlugs: ["data-fetching-and-caching", "server-actions"],
      },
      {
        id: "production-patterns",
        title: "Production Patterns",
        description:
          "Performance primitives (next/image, next/font, Suspense streaming, PPR), metadata and SEO, authentication with middleware, and deployment options.",
        routeSlugs: [
          "nextjs-performance-and-optimization",
          "metadata-and-seo",
          "authentication-and-middleware",
          "deployment-and-edge",
        ],
      },
      {
        id: "legacy-and-migration",
        title: "Pages Router & Migration",
        description:
          "The complete Pages Router surface — getServerSideProps, getStaticProps, ISR, API routes, useRouter — and the incremental migration path to the App Router.",
        routeSlugs: ["pages-router-and-migration"],
      },
      {
        id: "advanced-patterns-modern-nextjs",
        title: "Advanced Patterns & Modern Next.js",
        description:
          "Route segment config, navigation hooks, internationalization, and everything that changed in Next.js 15.",
        routeSlugs: [
          "route-segment-config",
          "navigation-hooks",
          "internationalization",
          "nextjs-15-and-observability",
        ],
      },
      {
        id: "testing",
        title: "Testing",
        description:
          "How to test every Next.js primitive: Server Components, Client Components, Route Handlers, Server Actions, and middleware.",
        routeSlugs: ["testing-nextjs"],
      },
      {
        id: "interview-prep",
        title: "Interview Prep",
        description:
          "30+ interview questions with ideal answers covering every major Next.js topic senior engineers are expected to know.",
        routeSlugs: ["nextjs-interview-questions"],
      },
    ],
  },
  {
    slug: "web-components",
    title: "Web Components",
    description:
      "Understand the platform-native component model. Custom Elements, Shadow DOM, HTML Templates, slots, lifecycle callbacks, and how Web Components interop with React and modern frameworks.",
    version: "1.0.0",
    icon: "🧩",
    accentColor: "#f97316",
    moduleCount: 6,
    totalHours: 3,
    comingSoon: false,
    routes: [
      {
        slug: "what-are-web-components",
        title: "What Are Web Components?",
        order: 0,
        estimatedMinutes: 20,
        tags: ["web-components", "fundamentals"],
        keywords: [
          "custom elements",
          "shadow DOM",
          "html templates",
          "es modules",
          "browser native",
          "framework agnostic",
          "platform primitives",
        ],
      },
      {
        slug: "custom-elements",
        title: "Custom Elements",
        order: 1,
        estimatedMinutes: 35,
        tags: ["web-components", "custom-elements", "lifecycle"],
        keywords: [
          "customElements.define",
          "connectedCallback",
          "disconnectedCallback",
          "attributeChangedCallback",
          "observedAttributes",
          "lifecycle callbacks",
          "element upgrade",
        ],
      },
      {
        slug: "shadow-dom",
        title: "Shadow DOM",
        order: 2,
        estimatedMinutes: 35,
        tags: ["web-components", "shadow-dom", "css"],
        keywords: [
          "shadow root",
          "attachShadow",
          "style encapsulation",
          "CSS custom properties",
          "::part()",
          "::slotted()",
          ":host",
          "shadow boundary",
        ],
      },
      {
        slug: "html-templates-and-slots",
        title: "HTML Templates & Slots",
        order: 4,
        estimatedMinutes: 30,
        tags: ["web-components", "templates", "slots", "composition"],
        keywords: [
          "template element",
          "cloneNode",
          "slot projection",
          "named slots",
          "slotchange event",
          "assignedElements",
          "::slotted",
        ],
      },
      {
        slug: "web-components-and-react",
        title: "Web Components & React",
        order: 5,
        estimatedMinutes: 30,
        tags: ["web-components", "react", "interop"],
        keywords: [
          "React interop",
          "attribute vs property",
          "React 18 web components",
          "React 19 web components",
          "wrapper pattern",
          "custom events React",
        ],
      },
      {
        slug: "web-components-in-practice",
        title: "Web Components in Practice",
        order: 6,
        estimatedMinutes: 35,
        tags: ["web-components", "lit", "design-system", "accessibility"],
        keywords: [
          "Lit",
          "design system",
          "ElementInternals",
          "form associated",
          "focus delegation",
          "ARIA shadow DOM",
          "when to use web components",
        ],
      },
    ],
    learningPath: [
      "what-are-web-components",
      "custom-elements",
      "shadow-dom",
      "html-templates-and-slots",
      "web-components-and-react",
      "web-components-in-practice",
    ],
    groups: [
      {
        id: "wc-foundations",
        title: "Platform Foundations",
        description: "The four specs, lifecycle, and DOM encapsulation",
        routeSlugs: ["what-are-web-components", "custom-elements", "shadow-dom"],
      },
      {
        id: "wc-advanced",
        title: "Composition & Integration",
        description: "Slots, React interop, real-world patterns, and Lit",
        routeSlugs: [
          "html-templates-and-slots",
          "web-components-and-react",
          "web-components-in-practice",
        ],
      },
    ],
  },
  {
    slug: "design-systems",
    title: "Design Systems",
    description:
      "From zero to hero on frontend design systems. Tokens, component architecture, theming, styling technologies, accessibility, Storybook, monorepo distribution, versioning, testing, Figma workflows, governance, real-world case studies, and a from-scratch capstone.",
    version: "1.0.0",
    icon: "🎨",
    accentColor: "#8b5cf6",
    moduleCount: 28,
    totalHours: 20,
    comingSoon: false,
    routes: [
      {
        slug: "what-is-a-design-system",
        title: "What Is a Design System?",
        order: 0,
        estimatedMinutes: 30,
        tags: ["design-systems", "foundations"],
        keywords: ["design system definition", "component library", "style guide", "single source of truth", "design language", "ROI", "anatomy", "maturity"],
      },
      {
        slug: "design-tokens",
        title: "Design Tokens",
        order: 1,
        estimatedMinutes: 40,
        tags: ["design-systems", "tokens", "foundations"],
        keywords: ["design tokens", "primitive tokens", "semantic tokens", "component tokens", "Style Dictionary", "DTCG", "token tiers", "CSS custom properties"],
      },
      {
        slug: "color-typography-and-spacing-systems",
        title: "Color, Typography & Spacing Systems",
        order: 2,
        estimatedMinutes: 40,
        tags: ["design-systems", "foundations", "visual"],
        keywords: ["color scale", "type scale", "modular scale", "spacing scale", "WCAG contrast", "OKLCH", "4-point grid", "fluid typography"],
      },
      {
        slug: "atomic-design-methodology",
        title: "Atomic Design Methodology",
        order: 3,
        estimatedMinutes: 35,
        tags: ["design-systems", "foundations", "components"],
        keywords: ["atomic design", "Brad Frost", "atoms molecules organisms", "templates pages", "component hierarchy", "composition", "component granularity", "design methodology"],
      },
      {
        slug: "component-architecture-and-api-design",
        title: "Component Architecture & API Design",
        order: 4,
        estimatedMinutes: 45,
        tags: ["design-systems", "components", "architecture"],
        keywords: ["component API", "variants", "compound components", "polymorphic", "asChild", "controlled uncontrolled", "headless", "cva", "composition"],
      },
      {
        slug: "styling-strategies-and-technologies",
        title: "Styling Strategies & Technologies",
        order: 5,
        estimatedMinutes: 45,
        tags: ["design-systems", "styling", "css"],
        keywords: ["CSS-in-JS", "Tailwind", "CSS Modules", "vanilla-extract", "Panda CSS", "zero-runtime", "styled-components", "RSC", "atomic CSS"],
      },
      {
        slug: "theming-and-multi-brand",
        title: "Theming & Multi-Brand Architecture",
        order: 6,
        estimatedMinutes: 40,
        tags: ["design-systems", "theming", "tokens"],
        keywords: ["theming", "dark mode", "multi-brand", "white label", "CSS variables", "prefers-color-scheme", "FOUC", "theme contract"],
      },
      {
        slug: "accessibility-in-design-systems",
        title: "Accessibility in Design Systems",
        order: 7,
        estimatedMinutes: 45,
        tags: ["design-systems", "accessibility", "a11y"],
        keywords: ["WCAG", "ARIA", "focus management", "focus trap", "Radix UI", "React Aria", "keyboard navigation", "roving tabindex", "screen reader"],
      },
      {
        slug: "documentation-and-storybook",
        title: "Documentation & Storybook",
        order: 8,
        estimatedMinutes: 40,
        tags: ["design-systems", "documentation", "storybook"],
        keywords: ["Storybook", "CSF", "MDX docs", "autodocs", "controls", "args", "usage guidelines", "Storybook addons"],
      },
      {
        slug: "monorepo-build-and-distribution",
        title: "Monorepo, Build & Distribution",
        order: 9,
        estimatedMinutes: 45,
        tags: ["design-systems", "monorepo", "build", "packaging"],
        keywords: ["monorepo", "pnpm workspace", "Turborepo", "npm publishing", "exports map", "tree-shaking", "tsup", "peer dependencies", "sideEffects"],
      },
      {
        slug: "versioning-and-releases",
        title: "Versioning & Releases",
        order: 10,
        estimatedMinutes: 35,
        tags: ["design-systems", "versioning", "releases"],
        keywords: ["semver", "Changesets", "breaking changes", "deprecation", "codemods", "migration guide", "changelog", "canary release"],
      },
      {
        slug: "testing-design-systems",
        title: "Testing Design Systems",
        order: 11,
        estimatedMinutes: 40,
        tags: ["design-systems", "testing", "quality"],
        keywords: ["visual regression", "Chromatic", "interaction tests", "Testing Library", "axe", "accessibility testing", "play function", "type tests"],
      },
      {
        slug: "figma-and-design-dev-workflow",
        title: "Figma & Design-Dev Workflow",
        order: 12,
        estimatedMinutes: 35,
        tags: ["design-systems", "figma", "workflow"],
        keywords: ["Figma variables", "Tokens Studio", "design handoff", "component parity", "auto layout", "design to code", "dev mode", "Figma API"],
      },
      {
        slug: "governance-contribution-and-adoption",
        title: "Governance, Contribution & Adoption",
        order: 13,
        estimatedMinutes: 35,
        tags: ["design-systems", "governance", "process"],
        keywords: ["governance model", "centralized federated", "RFC process", "contribution model", "adoption metrics", "component tiers", "deprecation policy"],
      },
      {
        slug: "case-studies-famous-design-systems",
        title: "Case Studies: Famous Design Systems",
        order: 14,
        estimatedMinutes: 35,
        tags: ["design-systems", "case-studies"],
        keywords: ["Material Design", "Shopify Polaris", "IBM Carbon", "Salesforce Lightning", "GitHub Primer", "Microsoft Fluent", "Adobe Spectrum", "build vs adopt"],
      },
      {
        slug: "building-a-design-system-from-scratch",
        title: "Building a Design System From Scratch",
        order: 15,
        estimatedMinutes: 50,
        tags: ["design-systems", "capstone", "project"],
        keywords: ["build design system", "capstone", "tokens to components", "monorepo setup", "MVP design system", "roadmap", "publish package"],
      },
      {
        slug: "layout-primitives",
        title: "Layout Primitives",
        order: 16,
        estimatedMinutes: 45,
        tags: ["design-systems", "layout", "components"],
        keywords: ["layout primitives", "Stack", "Cluster", "Grid", "Box", "Spacer", "Every Layout", "gap", "no margins"],
      },
      {
        slug: "forms-and-field-composition",
        title: "Forms & Field Composition",
        order: 17,
        estimatedMinutes: 50,
        tags: ["design-systems", "forms", "accessibility"],
        keywords: ["form field", "label association", "aria-describedby", "aria-invalid", "ElementInternals", "React Hook Form", "Zod", "validation", "useId"],
      },
      {
        slug: "building-a-complex-component",
        title: "Building a Complex Component",
        order: 18,
        estimatedMinutes: 55,
        tags: ["design-systems", "components", "accessibility"],
        keywords: ["combobox", "dialog", "Radix", "React Aria", "aria-activedescendant", "headless", "WAI-ARIA APG", "async search", "debounce"],
      },
      {
        slug: "icon-systems",
        title: "Icon Systems",
        order: 19,
        estimatedMinutes: 35,
        tags: ["design-systems", "icons", "build"],
        keywords: ["SVG icons", "SVGR", "SVGO", "icon sprite", "currentColor", "tree-shaking", "icon font", "accessible icons", "aria-hidden"],
      },
      {
        slug: "motion-and-animation",
        title: "Motion & Animation",
        order: 20,
        estimatedMinutes: 40,
        tags: ["design-systems", "motion", "animation"],
        keywords: ["motion tokens", "prefers-reduced-motion", "Framer Motion", "AnimatePresence", "exit animation", "starting-style", "easing", "transform opacity"],
      },
      {
        slug: "data-tables-and-complex-components",
        title: "Data Tables & Complex Components",
        order: 21,
        estimatedMinutes: 55,
        tags: ["design-systems", "components", "data"],
        keywords: ["data table", "TanStack Table", "virtualization", "TanStack Virtual", "sorting", "pagination", "row selection", "role grid", "responsive table"],
      },
      {
        slug: "responsive-and-container-queries",
        title: "Responsive & Container Queries",
        order: 22,
        estimatedMinutes: 35,
        tags: ["design-systems", "responsive", "css"],
        keywords: ["container queries", "@container", "breakpoint tokens", "viewport vs container", "cqi units", "fluid sizing", "clamp", "useBreakpoint"],
      },
      {
        slug: "i18n-rtl-and-bidi",
        title: "i18n, RTL & Bidi",
        order: 23,
        estimatedMinutes: 40,
        tags: ["design-systems", "i18n", "accessibility"],
        keywords: ["internationalization", "RTL", "logical properties", "margin-inline-start", "dir rtl", "bidi", "Intl", "text expansion", "icon mirroring", "localization"],
      },
      {
        slug: "ci-cd-pipelines",
        title: "CI/CD Pipelines",
        order: 24,
        estimatedMinutes: 40,
        tags: ["design-systems", "ci-cd", "automation"],
        keywords: ["GitHub Actions", "CI gates", "Chromatic CI", "size-limit", "bundle budget", "Changesets Action", "automated release", "Turborepo cache"],
      },
      {
        slug: "end-to-end-build-walkthrough",
        title: "End-to-End Build Walkthrough",
        order: 25,
        estimatedMinutes: 60,
        tags: ["design-systems", "capstone", "build"],
        keywords: ["build design system step by step", "pnpm workspace", "Style Dictionary", "tsup", "Storybook", "Changesets publish", "monorepo scaffold", "vertical slice"],
      },
      {
        slug: "practical-toolkit-checklists-templates",
        title: "Practical Toolkit: Checklists & Templates",
        order: 26,
        estimatedMinutes: 35,
        tags: ["design-systems", "process", "toolkit"],
        keywords: ["definition of done", "accessibility checklist", "component spec template", "RFC template", "PR template", "API review checklist", "contribution process"],
      },
      {
        slug: "design-systems-interview-questions",
        title: "Design Systems Interview Questions",
        order: 27,
        estimatedMinutes: 50,
        tags: ["design-systems", "interview", "questions"],
        keywords: ["design system interview", "component API interview", "token architecture", "theming interview", "versioning interview", "tradeoffs", "frontend architecture interview"],
      },
    ],
    learningPath: [
      "what-is-a-design-system",
      "design-tokens",
      "color-typography-and-spacing-systems",
      "atomic-design-methodology",
      "component-architecture-and-api-design",
      "styling-strategies-and-technologies",
      "theming-and-multi-brand",
      "accessibility-in-design-systems",
      "documentation-and-storybook",
      "monorepo-build-and-distribution",
      "versioning-and-releases",
      "testing-design-systems",
      "figma-and-design-dev-workflow",
      "governance-contribution-and-adoption",
      "case-studies-famous-design-systems",
      "building-a-design-system-from-scratch",
      "layout-primitives",
      "forms-and-field-composition",
      "building-a-complex-component",
      "icon-systems",
      "motion-and-animation",
      "data-tables-and-complex-components",
      "responsive-and-container-queries",
      "i18n-rtl-and-bidi",
      "ci-cd-pipelines",
      "end-to-end-build-walkthrough",
      "practical-toolkit-checklists-templates",
      "design-systems-interview-questions",
    ],
    groups: [
      {
        id: "ds-foundations",
        title: "Foundations",
        description:
          "What a design system is, the token layer that powers it, the color/type/spacing scales that give it visual coherence, and the Atomic Design model for structuring components.",
        routeSlugs: [
          "what-is-a-design-system",
          "design-tokens",
          "color-typography-and-spacing-systems",
          "atomic-design-methodology",
        ],
      },
      {
        id: "ds-component-engineering",
        title: "Component Engineering",
        description:
          "Designing component APIs, choosing a styling technology, building multi-brand theming, and baking in accessibility.",
        routeSlugs: [
          "component-architecture-and-api-design",
          "styling-strategies-and-technologies",
          "theming-and-multi-brand",
          "accessibility-in-design-systems",
        ],
      },
      {
        id: "ds-tooling-distribution",
        title: "Tooling & Distribution",
        description:
          "Documenting with Storybook, shipping packages from a monorepo, versioning safely, and testing at scale.",
        routeSlugs: [
          "documentation-and-storybook",
          "monorepo-build-and-distribution",
          "versioning-and-releases",
          "testing-design-systems",
        ],
      },
      {
        id: "ds-process-practice",
        title: "Process & Practice",
        description:
          "The Figma-to-code pipeline, governance and adoption, lessons from famous design systems, and a from-scratch strategic roadmap.",
        routeSlugs: [
          "figma-and-design-dev-workflow",
          "governance-contribution-and-adoption",
          "case-studies-famous-design-systems",
          "building-a-design-system-from-scratch",
        ],
      },
      {
        id: "ds-practitioner-build",
        title: "Practitioner: Building Components",
        description:
          "Hands-on, fully-coded builds: layout primitives, accessible forms, a complex component on a headless base, icon systems, motion, and data tables.",
        routeSlugs: [
          "layout-primitives",
          "forms-and-field-composition",
          "building-a-complex-component",
          "icon-systems",
          "motion-and-animation",
          "data-tables-and-complex-components",
        ],
      },
      {
        id: "ds-practitioner-ship",
        title: "Practitioner: Shipping & Operating",
        description:
          "Responsive/container queries, internationalization and RTL, CI/CD pipelines, a complete end-to-end build, and the checklists/templates that keep quality consistent.",
        routeSlugs: [
          "responsive-and-container-queries",
          "i18n-rtl-and-bidi",
          "ci-cd-pipelines",
          "end-to-end-build-walkthrough",
          "practical-toolkit-checklists-templates",
        ],
      },
      {
        id: "ds-interview",
        title: "Interview Prep",
        description: "Consolidated design-system interview questions across every topic, plus a system-design challenge.",
        routeSlugs: ["design-systems-interview-questions"],
      },
    ],
  },
];
