import type { AcademyManifest } from "@/lib/types/academy";

const manifest: AcademyManifest = {
  slug: "indeed-senior-react-nextjs-11802",
  title: "Indeed — Senior React/Next.js Prep",
  description:
    "Tailored prep for the Indeed Help Center role (#11802). Covers Contentstack CMS, Next.js SSR/SSG/ISR, GraphQL/Apollo, dynamic component registries, dynamic forms, performance, accessibility, Emotion/Storybook, system design, and behavioral interview prep.",
  version: "1.0.0",
  icon: "🎯",
  accentColor: "#2557d6",
  totalEstimatedMinutes: 920,
  routes: [
    {
      slug: "headless-cms-contentstack",
      title: "Headless CMS & Contentstack Architecture",
      order: 0,
      estimatedMinutes: 60,
      tags: ["cms", "contentstack", "headless", "architecture"],
      component: () => import("./modules/headless-cms-contentstack"),
    },
    {
      slug: "nextjs-cms-integration",
      title: "Next.js + CMS Integration Patterns",
      order: 1,
      estimatedMinutes: 45,
      tags: ["nextjs", "cms", "integration", "data-fetching"],
      component: () => import("./modules/nextjs-cms-integration"),
    },
    {
      slug: "graphql-for-cms",
      title: "GraphQL & Apollo for CMS",
      order: 2,
      estimatedMinutes: 50,
      tags: ["graphql", "apollo", "cms", "queries"],
      component: () => import("./modules/graphql-for-cms"),
    },
    {
      slug: "content-driven-component-architecture",
      title: "Content-Driven Component Architecture",
      order: 3,
      estimatedMinutes: 50,
      tags: ["react", "components", "cms", "architecture", "registry"],
      component: () => import("./modules/content-driven-component-architecture"),
    },
    {
      slug: "dynamic-forms-react",
      title: "Dynamic Forms in React",
      order: 4,
      estimatedMinutes: 40,
      tags: ["react", "forms", "dynamic", "validation"],
      component: () => import("./modules/dynamic-forms-react"),
    },
    {
      slug: "testing-strategy-jest-playwright",
      title: "Testing Strategy: Jest & Playwright",
      order: 5,
      estimatedMinutes: 50,
      tags: ["testing", "jest", "playwright", "e2e", "unit"],
      component: () => import("./modules/testing-strategy-jest-playwright"),
    },
    {
      slug: "performance-cms-sites",
      title: "Performance Optimization for CMS Sites",
      order: 6,
      estimatedMinutes: 40,
      tags: ["performance", "core-web-vitals", "nextjs", "optimization"],
      component: () => import("./modules/performance-cms-sites"),
    },
    {
      slug: "ssr-ssg-isr-decision",
      title: "SSR vs SSG vs ISR Decision Framework",
      order: 7,
      estimatedMinutes: 30,
      tags: ["nextjs", "ssr", "ssg", "isr", "rendering"],
      component: () => import("./modules/ssr-ssg-isr-decision"),
    },
    {
      slug: "accessibility-engineering",
      title: "Accessibility Engineering",
      order: 8,
      estimatedMinutes: 35,
      tags: ["accessibility", "a11y", "wcag", "aria"],
      component: () => import("./modules/accessibility-engineering"),
    },
    {
      slug: "css-in-js-emotion-storybook",
      title: "CSS-in-JS, Emotion & Storybook",
      order: 9,
      estimatedMinutes: 35,
      tags: ["css-in-js", "emotion", "storybook", "design-system"],
      component: () => import("./modules/css-in-js-emotion-storybook"),
    },
    {
      slug: "nodejs-backend-integration",
      title: "Node.js Backend Integration",
      order: 10,
      estimatedMinutes: 30,
      tags: ["nodejs", "backend", "api", "integration"],
      component: () => import("./modules/nodejs-backend-integration"),
    },
    {
      slug: "i18n-cms",
      title: "Internationalization with CMS",
      order: 11,
      estimatedMinutes: 30,
      tags: ["i18n", "internationalization", "cms", "localization"],
      component: () => import("./modules/i18n-cms"),
    },
    {
      slug: "cicd-gitlab",
      title: "CI/CD with GitLab",
      order: 12,
      estimatedMinutes: 25,
      tags: ["cicd", "gitlab", "deployment", "pipelines"],
      component: () => import("./modules/cicd-gitlab"),
    },
    {
      slug: "server-components-cms",
      title: "Server Components & CMS Boundaries",
      order: 13,
      estimatedMinutes: 30,
      tags: ["nextjs", "server-components", "rsc", "cms"],
      component: () => import("./modules/server-components-cms"),
    },
    {
      slug: "redis-caching",
      title: "Redis Caching for CMS APIs",
      order: 14,
      estimatedMinutes: 25,
      tags: ["redis", "caching", "cms", "performance"],
      component: () => import("./modules/redis-caching"),
    },
    {
      slug: "ab-testing-feature-flags",
      title: "A/B Testing & Feature Flags",
      order: 15,
      estimatedMinutes: 25,
      tags: ["ab-testing", "feature-flags", "nextjs", "edge", "middleware"],
      component: () => import("./modules/ab-testing-feature-flags"),
    },
    {
      slug: "docker-frontend",
      title: "Docker for Next.js Frontends",
      order: 16,
      estimatedMinutes: 20,
      tags: ["docker", "nextjs", "deployment", "devops", "containers"],
      component: () => import("./modules/docker-frontend"),
    },
    {
      slug: "system-design-help-center",
      title: "System Design: Help Center at Scale",
      order: 17,
      estimatedMinutes: 60,
      tags: ["system-design", "architecture", "help-center", "scalability", "indeed"],
      component: () => import("./modules/system-design-help-center"),
    },
    {
      slug: "behavioral-senior-ic",
      title: "Behavioral Interview: Senior IC",
      order: 18,
      estimatedMinutes: 45,
      tags: ["behavioral", "interview", "star", "senior", "soft-skills", "indeed"],
      component: () => import("./modules/behavioral-senior-ic"),
    },
    {
      slug: "contentful-deep-dive",
      title: "Contentful Deep Dive",
      order: 19,
      estimatedMinutes: 50,
      tags: ["contentful", "cms", "headless", "graphql", "sdk"],
      component: () => import("./modules/contentful-deep-dive"),
    },
    {
      slug: "stripe-integration",
      title: "Stripe Integration",
      order: 20,
      estimatedMinutes: 55,
      tags: ["stripe", "payments", "webhooks", "nextjs", "subscriptions"],
      component: () => import("./modules/stripe-integration"),
    },
    {
      slug: "strapi-deep-dive",
      title: "Strapi Deep Dive",
      order: 21,
      estimatedMinutes: 50,
      tags: ["strapi", "cms", "headless", "rest", "graphql", "self-hosted"],
      component: () => import("./modules/strapi-deep-dive"),
    },
    {
      slug: "cms-comparison",
      title: "CMS Comparison: Contentful vs Contentstack vs Strapi",
      order: 22,
      estimatedMinutes: 40,
      tags: ["cms", "contentful", "contentstack", "strapi", "comparison", "architecture"],
      component: () => import("./modules/cms-comparison"),
    },
  ],
  learningPath: [
    "headless-cms-contentstack",
    "nextjs-cms-integration",
    "graphql-for-cms",
    "content-driven-component-architecture",
    "dynamic-forms-react",
    "testing-strategy-jest-playwright",
    "performance-cms-sites",
    "ssr-ssg-isr-decision",
    "accessibility-engineering",
    "css-in-js-emotion-storybook",
    "nodejs-backend-integration",
    "i18n-cms",
    "cicd-gitlab",
    "server-components-cms",
    "redis-caching",
    "ab-testing-feature-flags",
    "docker-frontend",
    "system-design-help-center",
    "behavioral-senior-ic",
    "contentful-deep-dive",
    "stripe-integration",
    "strapi-deep-dive",
    "cms-comparison",
  ],
  groups: [
    {
      id: "cms-content-platform",
      title: "CMS & Content Platform",
      description:
        "Contentstack architecture, Next.js + CMS integration patterns, GraphQL/Apollo, and dynamic component systems.",
      routeSlugs: [
        "headless-cms-contentstack",
        "nextjs-cms-integration",
        "graphql-for-cms",
        "content-driven-component-architecture",
      ],
    },
    {
      id: "core-engineering",
      title: "Core Engineering",
      description:
        "Dynamic forms, testing strategy (Jest + Playwright), performance optimization, and rendering mode decisions.",
      routeSlugs: [
        "dynamic-forms-react",
        "testing-strategy-jest-playwright",
        "performance-cms-sites",
        "ssr-ssg-isr-decision",
      ],
    },
    {
      id: "production-dx",
      title: "Production & DX",
      description:
        "Accessibility, CSS-in-JS/Storybook, Node.js integration, i18n, CI/CD, and Server vs Client Component boundaries.",
      routeSlugs: [
        "accessibility-engineering",
        "css-in-js-emotion-storybook",
        "nodejs-backend-integration",
        "i18n-cms",
        "cicd-gitlab",
        "server-components-cms",
      ],
    },
    {
      id: "advanced-interview",
      title: "Advanced & Interview",
      description:
        "Redis caching, A/B testing, Docker, full system design, and behavioral interview preparation.",
      routeSlugs: [
        "redis-caching",
        "ab-testing-feature-flags",
        "docker-frontend",
        "system-design-help-center",
        "behavioral-senior-ic",
      ],
    },
    {
      id: "tools-integrations",
      title: "Tools & Integrations",
      description:
        "Contentful CMS deep dive (SDK, GraphQL, rich text, ISR), Stripe payment integration (PaymentIntents, Elements, webhooks, subscriptions), Strapi self-hosted CMS (REST API, populate syntax, v5 changes), and a head-to-head CMS comparison across all three platforms.",
      routeSlugs: [
        "contentful-deep-dive",
        "stripe-integration",
        "strapi-deep-dive",
        "cms-comparison",
      ],
    },
  ],
};

export default manifest;
