import type { AcademyManifest } from "@/lib/types/academy";

const manifest: AcademyManifest = {
  slug: "python-mastery",
  title: "Python Mastery",
  description:
    "Learn Python from fundamentals to advanced interview-ready topics. Designed for engineers coming from JavaScript/TypeScript — covering syntax, OOP, async, typing, testing, FastAPI, and coding interview patterns.",
  version: "1.0.0",
  icon: "🐍",
  accentColor: "#f59e0b",
  totalEstimatedMinutes: 910,
  routes: [
    {
      slug: "python-fundamentals",
      title: "Python Fundamentals",
      order: 0,
      estimatedMinutes: 30,
      tags: ["python", "fundamentals", "syntax"],
      component: () => import("./modules/python-fundamentals"),
    },
    {
      slug: "data-types-and-collections",
      title: "Data Types and Collections",
      order: 1,
      estimatedMinutes: 35,
      tags: ["python", "data-types", "collections", "mutability"],
      component: () => import("./modules/data-types-and-collections"),
    },
    {
      slug: "control-flow-and-loops",
      title: "Control Flow and Loops",
      order: 2,
      estimatedMinutes: 25,
      tags: ["python", "control-flow", "loops"],
      component: () => import("./modules/control-flow-and-loops"),
    },
    {
      slug: "functions-scope-and-arguments",
      title: "Functions, Scope, and Arguments",
      order: 3,
      estimatedMinutes: 30,
      tags: ["python", "functions", "scope", "closures"],
      component: () => import("./modules/functions-scope-and-arguments"),
    },
    {
      slug: "pythonic-code-and-comprehensions",
      title: "Pythonic Code and Comprehensions",
      order: 4,
      estimatedMinutes: 25,
      tags: ["python", "comprehensions", "pythonic", "pep8"],
      component: () => import("./modules/pythonic-code-and-comprehensions"),
    },
    {
      slug: "object-oriented-python",
      title: "Object-Oriented Python",
      order: 5,
      estimatedMinutes: 40,
      tags: ["python", "oop", "classes", "dataclasses"],
      component: () => import("./modules/object-oriented-python"),
    },
    {
      slug: "error-handling-and-debugging",
      title: "Error Handling and Debugging",
      order: 6,
      estimatedMinutes: 25,
      tags: ["python", "exceptions", "debugging"],
      component: () => import("./modules/error-handling-and-debugging"),
    },
    {
      slug: "modules-packages-and-envs",
      title: "Modules, Packages, and Environments",
      order: 7,
      estimatedMinutes: 25,
      tags: ["python", "modules", "packages", "venv", "pip"],
      component: () => import("./modules/modules-packages-and-envs"),
    },
    {
      slug: "file-io-and-standard-library",
      title: "File I/O and Standard Library",
      order: 8,
      estimatedMinutes: 30,
      tags: ["python", "file-io", "stdlib", "collections"],
      component: () => import("./modules/file-io-and-standard-library"),
    },
    {
      slug: "advanced-python-concepts",
      title: "Advanced Python Concepts",
      order: 9,
      estimatedMinutes: 40,
      tags: ["python", "generators", "decorators", "context-managers", "iterators"],
      component: () => import("./modules/advanced-python-concepts"),
    },
    {
      slug: "modern-python-typing",
      title: "Modern Python Typing",
      order: 10,
      estimatedMinutes: 30,
      tags: ["python", "typing", "type-hints", "pydantic"],
      component: () => import("./modules/modern-python-typing"),
    },
    {
      slug: "testing-with-pytest",
      title: "Testing with Pytest",
      order: 11,
      estimatedMinutes: 30,
      tags: ["python", "testing", "pytest", "fixtures"],
      component: () => import("./modules/testing-with-pytest"),
    },
    {
      slug: "async-python",
      title: "Async Python",
      order: 12,
      estimatedMinutes: 35,
      tags: ["python", "async", "asyncio", "concurrency"],
      component: () => import("./modules/async-python"),
    },
    {
      slug: "backend-with-fastapi",
      title: "Backend with FastAPI",
      order: 13,
      estimatedMinutes: 40,
      tags: ["python", "fastapi", "backend", "api"],
      component: () => import("./modules/backend-with-fastapi"),
    },
    {
      slug: "databases-and-orm-basics",
      title: "Databases and ORM Basics",
      order: 14,
      estimatedMinutes: 35,
      tags: ["python", "sqlalchemy", "orm", "database"],
      component: () => import("./modules/databases-and-orm-basics"),
    },
    {
      slug: "algorithms-and-data-structures-python",
      title: "Algorithms and Data Structures in Python",
      order: 15,
      estimatedMinutes: 60,
      tags: ["python", "algorithms", "data-structures", "interviews"],
      component: () => import("./modules/algorithms-and-data-structures-python"),
    },
    {
      slug: "python-interview-question-bank",
      title: "Python Interview Question Bank",
      order: 16,
      estimatedMinutes: 45,
      tags: ["python", "interviews", "questions"],
      component: () => import("./modules/python-interview-question-bank"),
    },
    {
      slug: "python-coding-challenges",
      title: "Python Coding Challenges",
      order: 17,
      estimatedMinutes: 60,
      tags: ["python", "challenges", "practice", "interviews"],
      component: () => import("./modules/python-coding-challenges"),
    },
    {
      slug: "final-python-interview-project",
      title: "Final Python Interview Project",
      order: 18,
      estimatedMinutes: 45,
      tags: ["python", "project", "fastapi", "interviews"],
      component: () => import("./modules/final-python-interview-project"),
    },
    {
      slug: "python-glossary-and-cheat-sheet",
      title: "Python Glossary and Cheat Sheet",
      order: 19,
      estimatedMinutes: 20,
      tags: ["python", "glossary", "cheat-sheet", "reference"],
      component: () => import("./modules/python-glossary-and-cheat-sheet"),
    },
    {
      slug: "python-for-js-ts-developers",
      title: "Python for JS/TS Developers",
      order: 20,
      estimatedMinutes: 30,
      tags: ["python", "javascript", "typescript", "comparison"],
      component: () => import("./modules/python-for-js-ts-developers"),
    },
    {
      slug: "python-frameworks-and-architecture",
      title: "Python Web Frameworks and Architecture",
      order: 21,
      estimatedMinutes: 50,
      tags: ["python", "django", "fastapi", "flask", "architecture", "backend"],
      component: () => import("./modules/python-frameworks-and-architecture"),
    },
    {
      slug: "python-concurrency",
      title: "Python Concurrency",
      order: 22,
      estimatedMinutes: 40,
      tags: ["python", "concurrency", "threading", "multiprocessing", "gil"],
      component: () => import("./modules/python-concurrency"),
    },
    {
      slug: "python-design-patterns",
      title: "Python Design Patterns",
      order: 23,
      estimatedMinutes: 45,
      tags: ["python", "design-patterns", "oop", "architecture"],
      component: () => import("./modules/python-design-patterns"),
    },
    {
      slug: "python-security",
      title: "Security in Python APIs",
      order: 24,
      estimatedMinutes: 40,
      tags: ["python", "security", "jwt", "fastapi", "backend"],
      component: () => import("./modules/python-security"),
    },
  ],
  learningPath: [
    "python-fundamentals",
    "data-types-and-collections",
    "control-flow-and-loops",
    "functions-scope-and-arguments",
    "pythonic-code-and-comprehensions",
    "object-oriented-python",
    "error-handling-and-debugging",
    "modules-packages-and-envs",
    "file-io-and-standard-library",
    "advanced-python-concepts",
    "modern-python-typing",
    "testing-with-pytest",
    "async-python",
    "backend-with-fastapi",
    "databases-and-orm-basics",
    "algorithms-and-data-structures-python",
    "python-interview-question-bank",
    "python-coding-challenges",
    "final-python-interview-project",
    "python-glossary-and-cheat-sheet",
    "python-for-js-ts-developers",
    "python-frameworks-and-architecture",
    "python-concurrency",
    "python-design-patterns",
    "python-security",
  ],
  groups: [
    {
      id: "python-foundations",
      title: "Python Foundations",
      description: "Syntax, data modeling, control flow, modules, and standard-library fluency.",
      routeSlugs: [
        "python-fundamentals",
        "data-types-and-collections",
        "control-flow-and-loops",
        "functions-scope-and-arguments",
        "pythonic-code-and-comprehensions",
        "object-oriented-python",
        "error-handling-and-debugging",
        "modules-packages-and-envs",
        "file-io-and-standard-library",
      ],
    },
    {
      id: "advanced-python-tooling",
      title: "Advanced Language & Tooling",
      description: "Modern Python features, typing, testing, and async mental models.",
      routeSlugs: [
        "advanced-python-concepts",
        "modern-python-typing",
        "testing-with-pytest",
        "async-python",
      ],
    },
    {
      id: "python-backend-foundations",
      title: "Backend & Data Foundations",
      description: "Building APIs and working with persistence layers in production-style Python systems.",
      routeSlugs: ["backend-with-fastapi", "databases-and-orm-basics"],
    },
    {
      id: "python-interview-practice",
      title: "Interview Prep & Applied Practice",
      description: "Algorithms, interview reps, coding drills, portfolio projects, and quick-reference review.",
      routeSlugs: [
        "algorithms-and-data-structures-python",
        "python-interview-question-bank",
        "python-coding-challenges",
        "final-python-interview-project",
        "python-glossary-and-cheat-sheet",
        "python-for-js-ts-developers",
      ],
    },
    {
      id: "production-python-architecture",
      title: "Production Python Architecture",
      description: "Framework choices, concurrency, design patterns, and API security for senior-level backend work.",
      routeSlugs: [
        "python-frameworks-and-architecture",
        "python-concurrency",
        "python-design-patterns",
        "python-security",
      ],
    },
  ],
};

export default manifest;
