import type { AcademyManifest } from "@/lib/types/academy";

const manifest: AcademyManifest = {
  slug: "system-design-aws",
  title: "System Design & AWS",
  description:
    "Master system design from first principles through AWS-powered production architecture. Built for senior engineers preparing for architecture interviews and real-world cloud design.",
  version: "1.0.0",
  icon: "🏗️",
  accentColor: "#f59e0b",
  totalEstimatedMinutes: 1315,
  routes: [
    {
      slug: "what-is-system-design",
      title: "What Is System Design?",
      order: 0,
      estimatedMinutes: 30,
      tags: ["fundamentals", "architecture", "overview"],
      component: () => import("./modules/what-is-system-design"),
    },
    {
      slug: "request-lifecycle",
      title: "The Full Request Lifecycle",
      order: 1,
      estimatedMinutes: 35,
      tags: ["networking", "dns", "http", "architecture"],
      component: () => import("./modules/request-lifecycle"),
    },
    {
      slug: "networking-fundamentals",
      title: "Networking Fundamentals",
      order: 2,
      estimatedMinutes: 40,
      tags: ["networking", "http", "tcp", "dns", "tls"],
      component: () => import("./modules/networking-fundamentals"),
    },
    {
      slug: "aws-cloud-networking",
      title: "AWS Cloud Networking (VPC)",
      order: 3,
      estimatedMinutes: 40,
      tags: ["aws", "vpc", "networking", "security-groups"],
      component: () => import("./modules/aws-cloud-networking"),
    },
    {
      slug: "traffic-entry-layer",
      title: "DNS, CDN, Load Balancers & API Gateway",
      order: 4,
      estimatedMinutes: 35,
      tags: ["aws", "cdn", "load-balancer", "api-gateway", "route53"],
      component: () => import("./modules/traffic-entry-layer"),
    },
    {
      slug: "stateless-horizontal-scaling",
      title: "Stateless Services & Horizontal Scaling",
      order: 5,
      estimatedMinutes: 30,
      tags: ["architecture", "scaling", "stateless", "ecs", "lambda"],
      component: () => import("./modules/stateless-horizontal-scaling"),
    },
    {
      slug: "sql-vs-nosql",
      title: "SQL vs NoSQL: Choosing the Right Database",
      order: 6,
      estimatedMinutes: 40,
      tags: ["databases", "sql", "nosql", "dynamodb", "postgres"],
      component: () => import("./modules/sql-vs-nosql"),
    },
    {
      slug: "dynamodb-deep-dive",
      title: "DynamoDB Deep Dive",
      order: 7,
      estimatedMinutes: 45,
      tags: ["aws", "dynamodb", "nosql", "databases"],
      component: () => import("./modules/dynamodb-deep-dive"),
    },
    {
      slug: "s3-object-storage",
      title: "S3 & Object Storage",
      order: 8,
      estimatedMinutes: 30,
      tags: ["aws", "s3", "storage", "object-storage"],
      component: () => import("./modules/s3-object-storage"),
    },
    {
      slug: "caching-strategies",
      title: "Caching Strategies",
      order: 9,
      estimatedMinutes: 35,
      tags: ["caching", "redis", "performance", "architecture"],
      component: () => import("./modules/caching-strategies"),
    },
    {
      slug: "performance-engineering",
      title: "Performance Engineering",
      order: 10,
      estimatedMinutes: 35,
      tags: ["performance", "latency", "throughput", "optimization"],
      component: () => import("./modules/performance-engineering"),
    },
    {
      slug: "queues-background-workers",
      title: "Queues & Background Workers",
      order: 11,
      estimatedMinutes: 35,
      tags: ["aws", "sqs", "queues", "async", "workers"],
      component: () => import("./modules/queues-background-workers"),
    },
    {
      slug: "event-driven-architecture",
      title: "Event-Driven Architecture",
      order: 12,
      estimatedMinutes: 40,
      tags: ["events", "pub-sub", "kafka", "eventbridge", "architecture"],
      component: () => import("./modules/event-driven-architecture"),
    },
    {
      slug: "reliability-availability",
      title: "Reliability, Availability & Fault Tolerance",
      order: 13,
      estimatedMinutes: 35,
      tags: ["reliability", "availability", "aws", "multi-az", "failover"],
      component: () => import("./modules/reliability-availability"),
    },
    {
      slug: "resilience-patterns",
      title: "Resilience Patterns: Retries, Circuit Breakers & Idempotency",
      order: 14,
      estimatedMinutes: 35,
      tags: ["resilience", "circuit-breaker", "retries", "idempotency", "distributed-systems"],
      component: () => import("./modules/resilience-patterns"),
    },
    {
      slug: "auth-architecture",
      title: "Authentication & Authorization Architecture",
      order: 15,
      estimatedMinutes: 40,
      tags: ["auth", "jwt", "oauth2", "cognito", "iam", "security"],
      component: () => import("./modules/auth-architecture"),
    },
    {
      slug: "cloud-security",
      title: "Cloud Security Fundamentals",
      order: 16,
      estimatedMinutes: 35,
      tags: ["security", "aws", "iam", "encryption", "secrets"],
      component: () => import("./modules/cloud-security"),
    },
    {
      slug: "observability",
      title: "Observability: Logs, Metrics & Traces",
      order: 17,
      estimatedMinutes: 35,
      tags: ["observability", "logs", "metrics", "traces", "cloudwatch"],
      component: () => import("./modules/observability"),
    },
    {
      slug: "incident-response",
      title: "Incident Response & Production Debugging",
      order: 18,
      estimatedMinutes: 30,
      tags: ["incidents", "debugging", "production", "runbooks", "postmortem"],
      component: () => import("./modules/incident-response"),
    },
    {
      slug: "cicd-deployment",
      title: "CI/CD & Deployment Strategies",
      order: 19,
      estimatedMinutes: 35,
      tags: ["ci-cd", "deployment", "docker", "github-actions", "aws"],
      component: () => import("./modules/cicd-deployment"),
    },
    {
      slug: "containers-orchestration",
      title: "Docker, ECS & Container Orchestration",
      order: 20,
      estimatedMinutes: 40,
      tags: ["docker", "containers", "ecs", "kubernetes", "lambda"],
      component: () => import("./modules/containers-orchestration"),
    },
    {
      slug: "infrastructure-as-code",
      title: "Infrastructure as Code",
      order: 21,
      estimatedMinutes: 35,
      tags: ["iac", "terraform", "cdk", "cloudformation", "pulumi"],
      component: () => import("./modules/infrastructure-as-code"),
    },
    {
      slug: "latency-numbers",
      title: "Latency Numbers & Back-of-Envelope Math",
      order: 22,
      estimatedMinutes: 25,
      tags: ["performance", "estimation", "interviews", "numbers"],
      component: () => import("./modules/latency-numbers"),
    },
    {
      slug: "cap-theorem-tradeoffs",
      title: "CAP Theorem, Consistency & Tradeoffs",
      order: 23,
      estimatedMinutes: 30,
      tags: ["distributed-systems", "cap-theorem", "consistency", "tradeoffs"],
      component: () => import("./modules/cap-theorem-tradeoffs"),
    },
    {
      slug: "aws-service-map",
      title: "AWS Service Map",
      order: 24,
      estimatedMinutes: 40,
      tags: ["aws", "overview", "services", "architecture"],
      component: () => import("./modules/aws-service-map"),
    },
    {
      slug: "aws-complete-architecture",
      title: "Designing a Complete AWS Architecture",
      order: 25,
      estimatedMinutes: 45,
      tags: ["aws", "architecture", "system-design", "production"],
      component: () => import("./modules/aws-complete-architecture"),
    },
    {
      slug: "interview-framework",
      title: "System Design Interview Framework",
      order: 26,
      estimatedMinutes: 30,
      tags: ["interviews", "system-design", "framework", "communication"],
      component: () => import("./modules/interview-framework"),
    },
    {
      slug: "system-design-practice",
      title: "System Design Practice Problems",
      order: 27,
      estimatedMinutes: 60,
      tags: ["interviews", "practice", "system-design", "architecture"],
      component: () => import("./modules/system-design-practice"),
    },
    {
      slug: "capstone-cv-builder",
      title: "Capstone: Production System Design Document",
      order: 28,
      estimatedMinutes: 50,
      tags: ["capstone", "system-design", "aws", "production", "interviews"],
      component: () => import("./modules/capstone-cv-builder"),
    },
  ],
  learningPath: [
    "what-is-system-design",
    "request-lifecycle",
    "networking-fundamentals",
    "aws-cloud-networking",
    "traffic-entry-layer",
    "stateless-horizontal-scaling",
    "sql-vs-nosql",
    "dynamodb-deep-dive",
    "s3-object-storage",
    "caching-strategies",
    "performance-engineering",
    "queues-background-workers",
    "event-driven-architecture",
    "reliability-availability",
    "resilience-patterns",
    "auth-architecture",
    "cloud-security",
    "observability",
    "incident-response",
    "cicd-deployment",
    "containers-orchestration",
    "infrastructure-as-code",
    "latency-numbers",
    "cap-theorem-tradeoffs",
    "aws-service-map",
    "aws-complete-architecture",
    "interview-framework",
    "system-design-practice",
    "capstone-cv-builder",
  ],
  groups: [
    {
      id: "request-path-compute",
      title: "Request Path & Compute Foundations",
      description: "The end-to-end request lifecycle, cloud networking, and stateless service architecture.",
      routeSlugs: [
        "what-is-system-design",
        "request-lifecycle",
        "networking-fundamentals",
        "aws-cloud-networking",
        "traffic-entry-layer",
        "stateless-horizontal-scaling",
      ],
    },
    {
      id: "data-storage-performance",
      title: "Data, Storage & Performance",
      description: "Databases, object storage, caching, and the core performance tradeoffs behind distributed systems.",
      routeSlugs: [
        "sql-vs-nosql",
        "dynamodb-deep-dive",
        "s3-object-storage",
        "caching-strategies",
        "performance-engineering",
      ],
    },
    {
      id: "async-reliability-ops",
      title: "Async Systems, Reliability & Operations",
      description: "Queues, events, resilience, security, observability, and production operations.",
      routeSlugs: [
        "queues-background-workers",
        "event-driven-architecture",
        "reliability-availability",
        "resilience-patterns",
        "auth-architecture",
        "cloud-security",
        "observability",
        "incident-response",
        "cicd-deployment",
        "containers-orchestration",
      ],
    },
    {
      id: "infra-tradeoffs",
      title: "Infrastructure & Distributed Systems Tradeoffs",
      description: "Infrastructure as code, architecture estimation, consistency tradeoffs, and AWS solution design.",
      routeSlugs: [
        "infrastructure-as-code",
        "latency-numbers",
        "cap-theorem-tradeoffs",
        "aws-service-map",
        "aws-complete-architecture",
      ],
    },
    {
      id: "system-design-interview-capstone",
      title: "Interview Practice & Capstone",
      description: "Structured system-design interview reps and a final architecture deliverable.",
      routeSlugs: [
        "interview-framework",
        "system-design-practice",
        "capstone-cv-builder",
      ],
    },
  ],
};

export default manifest;
