import type { AcademyManifest } from "@/lib/types/academy";

/**
 * growth-life-client-api Mastery
 *
 * A deep, repo-grounded academy that takes a reader from zero knowledge to
 * full expertise on the Flex `growth-life-client-api` service — the
 * template-driven Koa BFF that serves UI screens and action executions for
 * Disney+, Hulu, and ESPN+.
 *
 * Modules are grouped into four learning paths that mirror the repo's real
 * mental layers: Foundations, the Screen Pipeline, Execution & Experimentation,
 * and Platform/Testing/Mastery. The academy is built group-by-group; routes and
 * groups are added as each module file lands so the build stays green.
 */
const manifest: AcademyManifest = {
  slug: "growth-life-client-api-mastery",
  title: "growth-life-client-api Mastery",
  description:
    "Become an expert on Flex's growth-life-client-api — the template-driven Koa BFF behind Disney+, Hulu, and ESPN+ subscription screens. Learn the request lifecycle, the GLO→Flex type systems, the screen pipeline, backends, element builders, executions, feature flags, experimentation, the platform migration, and the testing standards, all grounded in the real codebase.",
  version: "1.1.0",
  icon: "🧬",
  accentColor: "#113ccf",
  totalEstimatedMinutes: 1015,
  routes: [
    {
      slug: "what-is-growth-life-client-api",
      title: "What Is growth-life-client-api",
      order: 0,
      estimatedMinutes: 40,
      tags: ["foundations", "architecture", "bff", "flex", "disney"],
      keywords: [
        "template driven",
        "koa bff",
        "screens vs executions",
        "growth-life-client-templates",
        "s3 templates",
        "disney hulu espn",
      ],
      component: () => import("./modules/what-is-growth-life-client-api"),
    },
    {
      slug: "server-and-request-lifecycle",
      title: "Server & Request Lifecycle",
      order: 1,
      estimatedMinutes: 55,
      tags: ["foundations", "koa", "middleware", "flexcontext", "headers"],
      keywords: [
        "app.ts",
        "server.ts",
        "koa middleware",
        "FlexContext",
        "flexContextRouteHandler",
        "standardHeaders",
        "regionConfig",
        "featureSet",
      ],
      component: () => import("./modules/server-and-request-lifecycle"),
    },
    {
      slug: "the-two-type-systems",
      title: "The Two Type Systems: GLO vs Flex",
      order: 2,
      estimatedMinutes: 55,
      tags: ["foundations", "types", "conversion", "glo", "flex"],
      keywords: [
        "GLO types",
        "Flex types",
        "conversion wrappers",
        "domain/common",
        "getOffers",
        "getAgreementDetails",
        "type safety",
      ],
      component: () => import("./modules/the-two-type-systems"),
    },
    {
      slug: "template-driven-rendering",
      title: "Template-Driven Rendering",
      order: 3,
      estimatedMinutes: 55,
      tags: ["foundations", "templates", "ejs", "cypher", "localization"],
      keywords: [
        "EJS",
        "fillTemplate",
        "template configuration",
        "screen contract type",
        "cypher keys",
        "dictionary",
        "localization",
      ],
      component: () => import("./modules/template-driven-rendering"),
    },
    {
      slug: "routes-and-validation",
      title: "Routes & Validation",
      order: 4,
      estimatedMinutes: 45,
      tags: ["pipeline", "routes", "joi", "openapi", "v1", "v2"],
      keywords: [
        "joi validation",
        "flexContextRouteHandler",
        ".unknown()",
        "v1 vs v2",
        "getFlexResourceFilters",
        "datadog tagging",
        "build:swagger",
        "openapi.yaml",
      ],
      component: () => import("./modules/routes-and-validation"),
    },
    {
      slug: "backends-and-integrations",
      title: "Backends & Integrations",
      order: 5,
      estimatedMinutes: 50,
      tags: ["pipeline", "backends", "glo", "ipse", "cypher", "promise-all"],
      keywords: [
        "GrowthLifeOrchestratorClient",
        "retrieveOffersV2",
        "cached client",
        "Promise.all",
        "IPSE",
        "offers service",
        "weaponX",
        "parallel fetch",
      ],
      component: () => import("./modules/backends-and-integrations"),
    },
    {
      slug: "domain-layer-and-conversion",
      title: "Domain Layer & Conversion",
      order: 6,
      estimatedMinutes: 50,
      tags: ["pipeline", "domain", "conversion", "flex", "models"],
      keywords: [
        "domain/common",
        "domain/models",
        "getAgreementDetails",
        "conversion wrapper",
        "shared selectors",
        "screen contract types",
        "defensive defaults",
      ],
      component: () => import("./modules/domain-layer-and-conversion"),
    },
    {
      slug: "screen-services",
      title: "Screen Services",
      order: 7,
      estimatedMinutes: 55,
      tags: ["pipeline", "services", "orchestration", "fillTemplate"],
      keywords: [
        "buildXScreen",
        "orchestration",
        "five step shape",
        "Promise.all",
        "fillTemplate",
        "function registry",
        "no-screen-function-registry",
        "migrationConfig",
      ],
      component: () => import("./modules/screen-services"),
    },
    {
      slug: "element-builders-and-cypher",
      title: "Element Builders & Cypher",
      order: 8,
      estimatedMinutes: 50,
      tags: ["pipeline", "elements", "cypher", "localization", "copy"],
      keywords: [
        "toInteractionElement",
        "toCopy",
        "InteractionElement",
        "cypher keys",
        "dictionary",
        "toCurrencyVariable",
        "Pattern 1",
        "localization",
      ],
      component: () => import("./modules/element-builders-and-cypher"),
    },
    {
      slug: "metrics-and-analytics",
      title: "Metrics & Analytics",
      order: 9,
      estimatedMinutes: 45,
      tags: ["pipeline", "metrics", "analytics", "glimpse"],
      keywords: [
        "buildPageViewMetricsDataV2",
        "buildContainerViewMetricsDataV2",
        "buildInteractionMetricsDataV2",
        "elementIndex",
        "Glimpse",
        "ESPN Adobe",
        "HITS",
        "Tealium",
      ],
      component: () => import("./modules/metrics-and-analytics"),
    },
    {
      slug: "action-executions",
      title: "Action Executions",
      order: 10,
      estimatedMinutes: 50,
      tags: ["execution", "mutations", "cancel", "switch", "payments"],
      keywords: [
        "domain/execution",
        "cancelSubscriptionExecution",
        "state change",
        "guards",
        "preconditions",
        "idempotency",
        "no experiments in executions",
      ],
      component: () => import("./modules/action-executions"),
    },
    {
      slug: "feature-flags",
      title: "Feature Flags",
      order: 11,
      estimatedMinutes: 40,
      tags: ["execution", "flags", "launchdarkly", "rollout"],
      keywords: [
        "FlagKeys",
        "FeatureFlag",
        "getFeatureFlagValue",
        "defaultValue",
        "LaunchDarkly",
        "two file pattern",
        "cleanup jsdoc",
      ],
      component: () => import("./modules/feature-flags"),
    },
    {
      slug: "experimentation",
      title: "Experimentation",
      order: 12,
      estimatedMinutes: 65,
      tags: ["execution", "experiments", "weaponx", "featureset", "abtest"],
      keywords: [
        "WeaponX",
        "getExperimentTreatment",
        "FeatureSet pattern",
        "treatment undefined trap",
        "variants registry treatment",
        "initialize cleanup productionalize",
        "template config vs service code",
      ],
      component: () => import("./modules/experimentation"),
    },
    {
      slug: "platform-migration",
      title: "Platform Migration",
      order: 13,
      estimatedMinutes: 55,
      tags: ["mastery", "platform", "migration", "parity"],
      keywords: [
        "src/platform",
        "migrationConfig",
        "createScreenConfig",
        "pipeline assembly",
        "dual path",
        "change both",
        "parity tests",
        "migrating qa deprecated",
      ],
      component: () => import("./modules/platform-migration"),
    },
    {
      slug: "testing-standards",
      title: "Testing Standards",
      order: 14,
      estimatedMinutes: 50,
      tags: ["mastery", "testing", "mocks", "factories"],
      keywords: [
        "TESTING.md",
        "setupMocks",
        "MockOverrides",
        "factory functions",
        "behavioral assertions",
        "mock GLO client not wrapper",
        "legacy test policy",
        "behavior matrix",
      ],
      component: () => import("./modules/testing-standards"),
    },
    {
      slug: "build-tooling-and-ci",
      title: "Build Tooling & CI",
      order: 15,
      estimatedMinutes: 45,
      tags: ["mastery", "tooling", "ci", "codegen"],
      keywords: [
        "build:typeguards",
        "build:swagger",
        "generated schemas",
        "import rules",
        "! aliases",
        "no-screen-function-registry",
        "CI checks",
        "HULU_ENV",
      ],
      component: () => import("./modules/build-tooling-and-ci"),
    },
    {
      slug: "mastery-capstone",
      title: "Mastery Capstone",
      order: 16,
      estimatedMinutes: 50,
      tags: ["mastery", "capstone", "integration", "debugging"],
      keywords: [
        "end to end screen",
        "debug by symptom",
        "architecture tradeoffs",
        "pre-push checklist",
        "full request flow",
        "layer triage",
      ],
      component: () => import("./modules/mastery-capstone"),
    },
    {
      slug: "caching-and-performance",
      title: "Caching & Performance",
      order: 17,
      estimatedMinutes: 45,
      tags: ["cross-cutting", "caching", "performance", "valkey"],
      keywords: [
        "CacheInterface",
        "ValkeyCache",
        "retrieve dataFetcher",
        "CachedXClient decorator",
        "TTL cache key",
        "read-through cache",
        "Promise.all",
      ],
      component: () => import("./modules/caching-and-performance"),
    },
    {
      slug: "error-handling-and-resilience",
      title: "Error Handling & Resilience",
      order: 18,
      estimatedMinutes: 50,
      tags: ["cross-cutting", "errors", "resilience", "observability"],
      keywords: [
        "ApplicationError",
        "BaseError taxonomy",
        "errorHandler executionErrorHandler proxyErrorHandler",
        "invalidStateResponse",
        "logLevel",
        "logWithSampling",
        "mask PII",
        "Datadog tracing",
        "graceful degradation",
      ],
      component: () => import("./modules/error-handling-and-resilience"),
    },
    {
      slug: "context-region-and-eligibility",
      title: "Context, Region & Eligibility",
      order: 19,
      estimatedMinutes: 45,
      tags: ["cross-cutting", "region", "context", "eligibility"],
      keywords: [
        "RegionConfiguration",
        "REGION_EXPERIENCE_MAP",
        "regionExperience LATAM EMEA APAC",
        "DeviceContext",
        "SessionAccess isAuthenticated",
        "eligibilityRules",
        "flexEligibilityService",
        "redirectHandler",
      ],
      component: () => import("./modules/context-region-and-eligibility"),
    },
  ],
  groups: [
    {
      id: "foundations",
      title: "Path 1 — Foundations & Architecture",
      description:
        "The mental model: what this service is, how a request flows through Koa into a rendered screen, the two type systems, and template-driven rendering.",
      routeSlugs: [
        "what-is-growth-life-client-api",
        "server-and-request-lifecycle",
        "the-two-type-systems",
        "template-driven-rendering",
      ],
    },
    {
      id: "screen-pipeline",
      title: "Path 2 — The Screen Pipeline (Request → UI)",
      description:
        "The end-to-end pipeline: route validation, the backends fan-out, GLO→Flex conversion, screen-service orchestration, element/Cypher builders, and analytics.",
      routeSlugs: [
        "routes-and-validation",
        "backends-and-integrations",
        "domain-layer-and-conversion",
        "screen-services",
        "element-builders-and-cypher",
        "metrics-and-analytics",
      ],
    },
    {
      id: "execution-experimentation",
      title: "Path 3 — Execution, Flags & Experimentation",
      description:
        "The write side and the levers: state-changing action executions, LaunchDarkly feature flags, and the WeaponX experimentation system with the FeatureSet pattern.",
      routeSlugs: ["action-executions", "feature-flags", "experimentation"],
    },
    {
      id: "mastery",
      title: "Path 4 — Platform Migration, Testing & Mastery",
      description:
        "The professional layer: the legacy→platform migration and its change-both discipline, the testing standards, the codegen/CI tooling, and a capstone that ties every layer together.",
      routeSlugs: [
        "platform-migration",
        "testing-standards",
        "build-tooling-and-ci",
        "mastery-capstone",
      ],
    },
    {
      id: "cross-cutting",
      title: "Path 5 — Cross-Cutting Concerns & Operability",
      description:
        "The concerns that span every request: caching and performance, the error taxonomy and resilience/observability, and how region, device, session, and eligibility context drive business rules.",
      routeSlugs: [
        "caching-and-performance",
        "error-handling-and-resilience",
        "context-region-and-eligibility",
      ],
    },
  ],
  learningPath: [
    "what-is-growth-life-client-api",
    "server-and-request-lifecycle",
    "the-two-type-systems",
    "template-driven-rendering",
    "routes-and-validation",
    "backends-and-integrations",
    "domain-layer-and-conversion",
    "screen-services",
    "element-builders-and-cypher",
    "metrics-and-analytics",
    "action-executions",
    "feature-flags",
    "experimentation",
    "platform-migration",
    "testing-standards",
    "build-tooling-and-ci",
    "mastery-capstone",
    "caching-and-performance",
    "error-handling-and-resilience",
    "context-region-and-eligibility",
  ],
};

export default manifest;
