import type { AcademyManifest } from "@/lib/types/academy";

const manifest: AcademyManifest = {
  slug: "express-backend",
  title: "Express.js & Backend Engineering",
  description:
    "Master Express.js from fundamentals to production — REST design, authentication, authorization, caching, security, testing, and performance patterns for Node.js backends.",
  version: "1.0.0",
  icon: "🚀",
  accentColor: "#10b981",
  totalEstimatedMinutes: 1260,
  routes: [
    {
      slug: "express-fundamentals",
      title: "Express Fundamentals",
      order: 0,
      estimatedMinutes: 30,
      tags: ["express", "fundamentals", "routing"],
      component: () => import("./modules/express-fundamentals"),
    },
    {
      slug: "middleware-pipeline",
      title: "Middleware & the Request Pipeline",
      order: 1,
      estimatedMinutes: 35,
      tags: ["express", "middleware", "pipeline"],
      component: () => import("./modules/middleware-pipeline"),
    },
    {
      slug: "rest-api-design",
      title: "REST API Design",
      order: 2,
      estimatedMinutes: 35,
      tags: ["rest", "api-design", "http"],
      component: () => import("./modules/rest-api-design"),
    },
    {
      slug: "api-contracts-openapi",
      title: "API Contracts & OpenAPI",
      order: 3,
      estimatedMinutes: 50,
      tags: ["openapi", "contracts", "swagger", "api-design", "testing"],
      component: () => import("./modules/api-contracts-openapi"),
    },
    {
      slug: "validation-error-handling",
      title: "Validation & Error Handling",
      order: 4,
      estimatedMinutes: 35,
      tags: ["validation", "zod", "error-handling"],
      component: () => import("./modules/validation-error-handling"),
    },
    {
      slug: "authentication-jwt",
      title: "Authentication with JWT",
      order: 5,
      estimatedMinutes: 40,
      tags: ["auth", "jwt", "security"],
      component: () => import("./modules/authentication-jwt"),
    },
    {
      slug: "authentication-sessions",
      title: "Authentication with Sessions & Cookies",
      order: 6,
      estimatedMinutes: 35,
      tags: ["auth", "sessions", "cookies", "csrf"],
      component: () => import("./modules/authentication-sessions"),
    },
    {
      slug: "authorization-rbac",
      title: "Authorization: RBAC & Permissions",
      order: 7,
      estimatedMinutes: 35,
      tags: ["authorization", "rbac", "abac", "permissions"],
      component: () => import("./modules/authorization-rbac"),
    },
    {
      slug: "database-integration",
      title: "Database Integration",
      order: 8,
      estimatedMinutes: 40,
      tags: ["database", "prisma", "postgresql", "orm"],
      component: () => import("./modules/database-integration"),
    },
    {
      slug: "advanced-database-engineering",
      title: "Advanced Database Engineering",
      order: 9,
      estimatedMinutes: 50,
      tags: ["database", "indexes", "transactions", "query-plans", "scaling"],
      component: () => import("./modules/advanced-database-engineering"),
    },
    {
      slug: "caching-redis",
      title: "Caching with Redis",
      order: 10,
      estimatedMinutes: 35,
      tags: ["redis", "caching", "performance"],
      component: () => import("./modules/caching-redis"),
    },
    {
      slug: "security-best-practices",
      title: "Security Best Practices",
      order: 11,
      estimatedMinutes: 40,
      tags: ["security", "helmet", "cors", "owasp"],
      component: () => import("./modules/security-best-practices"),
    },
    {
      slug: "testing-express",
      title: "Testing Express APIs",
      order: 12,
      estimatedMinutes: 35,
      tags: ["testing", "supertest", "vitest", "integration-tests"],
      component: () => import("./modules/testing-express"),
    },
    {
      slug: "production-ready",
      title: "Production-Ready Express",
      order: 13,
      estimatedMinutes: 40,
      tags: ["production", "performance", "monitoring", "pm2"],
      component: () => import("./modules/production-ready"),
    },
    {
      slug: "advanced-node-runtime",
      title: "Advanced Node.js Runtime",
      order: 14,
      estimatedMinutes: 55,
      tags: ["node", "streams", "backpressure", "worker-threads", "memory"],
      component: () => import("./modules/advanced-node-runtime"),
    },
    {
      slug: "observability-diagnostics",
      title: "Observability & Diagnostics",
      order: 15,
      estimatedMinutes: 55,
      tags: ["observability", "opentelemetry", "logging", "metrics", "profiling"],
      component: () => import("./modules/observability-diagnostics"),
    },
    {
      slug: "background-jobs-queues",
      title: "Background Jobs & Queues",
      order: 16,
      estimatedMinutes: 50,
      tags: ["queues", "bullmq", "redis", "workers", "outbox"],
      component: () => import("./modules/background-jobs-queues"),
    },
    {
      slug: "deployment-operations",
      title: "Deployment & Operations",
      order: 17,
      estimatedMinutes: 50,
      tags: ["docker", "kubernetes", "deployment", "operations", "zero-downtime"],
      component: () => import("./modules/deployment-operations"),
    },
    {
      slug: "senior-system-design",
      title: "Senior Backend System Design",
      order: 18,
      estimatedMinutes: 55,
      tags: ["system-design", "architecture", "senior", "scalability"],
      component: () => import("./modules/senior-system-design"),
    },
    {
      slug: "interview-prep",
      title: "Interview Questions & Code Challenges",
      order: 19,
      estimatedMinutes: 60,
      tags: ["interview", "questions", "code-challenges", "prep"],
      component: () => import("./modules/interview-prep"),
    },
    {
      slug: "interview-01-node-fundamentals",
      title: "Interview: Node.js Fundamentals",
      order: 20,
      estimatedMinutes: 30,
      tags: ["interview", "node", "fundamentals", "v8", "libuv"],
      component: () => import("./modules/interview-01-node-fundamentals"),
    },
    {
      slug: "interview-02-event-loop",
      title: "Interview: Event Loop & Async Behavior",
      order: 21,
      estimatedMinutes: 35,
      tags: ["interview", "event-loop", "async", "worker-threads", "cluster"],
      component: () => import("./modules/interview-02-event-loop"),
    },
    {
      slug: "interview-03-promises-async",
      title: "Interview: Promises, Async/Await & Error Handling",
      order: 22,
      estimatedMinutes: 35,
      tags: ["interview", "promises", "async-await", "error-handling", "try-catch"],
      component: () => import("./modules/interview-03-promises-async"),
    },
    {
      slug: "interview-04-express-fundamentals",
      title: "Interview: Express.js Fundamentals",
      order: 23,
      estimatedMinutes: 40,
      tags: ["interview", "express", "middleware", "routing", "architecture"],
      component: () => import("./modules/interview-04-express-fundamentals"),
    },
    {
      slug: "interview-05-rest-api-design",
      title: "Interview: REST API Design",
      order: 24,
      estimatedMinutes: 40,
      tags: ["interview", "rest", "http", "pagination", "idempotency", "rate-limiting"],
      component: () => import("./modules/interview-05-rest-api-design"),
    },
    {
      slug: "interview-06-auth",
      title: "Interview: Authentication & Authorization",
      order: 25,
      estimatedMinutes: 45,
      tags: ["interview", "jwt", "sessions", "oauth", "rbac", "bcrypt", "security"],
      component: () => import("./modules/interview-06-auth"),
    },
    {
      slug: "interview-07-security",
      title: "Interview: Security",
      order: 26,
      estimatedMinutes: 40,
      tags: ["interview", "security", "owasp", "xss", "csrf", "cors", "injection", "helmet"],
      component: () => import("./modules/interview-07-security"),
    },
    {
      slug: "interview-08-databases",
      title: "Interview: Databases & Data Access",
      order: 27,
      estimatedMinutes: 45,
      tags: ["interview", "database", "orm", "prisma", "sql", "nosql", "transactions", "acid", "indexes", "migrations"],
      component: () => import("./modules/interview-08-databases"),
    },
    {
      slug: "interview-09-architecture",
      title: "Interview: Architecture & Clean Code",
      order: 28,
      estimatedMinutes: 45,
      tags: ["interview", "architecture", "clean-code", "dependency-injection", "repository-pattern", "dtos", "monolith", "microservices"],
      component: () => import("./modules/interview-09-architecture"),
    },
    {
      slug: "interview-10-testing",
      title: "Interview: Testing",
      order: 29,
      estimatedMinutes: 45,
      tags: ["interview", "testing", "vitest", "supertest", "mocks", "coverage", "integration-tests"],
      component: () => import("./modules/interview-10-testing"),
    },
  ],
  learningPath: [
    "express-fundamentals",
    "middleware-pipeline",
    "rest-api-design",
    "api-contracts-openapi",
    "validation-error-handling",
    "authentication-jwt",
    "authentication-sessions",
    "authorization-rbac",
    "database-integration",
    "advanced-database-engineering",
    "caching-redis",
    "security-best-practices",
    "testing-express",
    "production-ready",
    "advanced-node-runtime",
    "observability-diagnostics",
    "background-jobs-queues",
    "deployment-operations",
    "senior-system-design",
    "interview-prep",
    "interview-01-node-fundamentals",
    "interview-02-event-loop",
    "interview-03-promises-async",
    "interview-04-express-fundamentals",
    "interview-05-rest-api-design",
    "interview-06-auth",
    "interview-07-security",
    "interview-08-databases",
    "interview-09-architecture",
    "interview-10-testing",
  ],
  groups: [
    {
      id: "express-core",
      title: "Express Core",
      description: "The fundamental building blocks: routing, middleware, REST design, OpenAPI contracts, and robust error handling.",
      routeSlugs: [
        "express-fundamentals",
        "middleware-pipeline",
        "rest-api-design",
        "api-contracts-openapi",
        "validation-error-handling",
      ],
    },
    {
      id: "auth-authorization",
      title: "Authentication & Authorization",
      description: "JWT, session-based auth, CSRF, RBAC, ABAC, and composable permission middleware.",
      routeSlugs: [
        "authentication-jwt",
        "authentication-sessions",
        "authorization-rbac",
      ],
    },
    {
      id: "data-caching",
      title: "Data & Caching",
      description: "Database integration patterns, Prisma, indexes, query plans, transactions, Redis caching strategies, and HTTP cache headers.",
      routeSlugs: [
        "database-integration",
        "advanced-database-engineering",
        "caching-redis",
      ],
    },
    {
      id: "production-engineering",
      title: "Production Engineering",
      description: "Security hardening, integration testing with supertest, clustering, graceful shutdown, structured logging, monitoring, deployment, and runtime diagnostics.",
      routeSlugs: [
        "security-best-practices",
        "testing-express",
        "production-ready",
        "advanced-node-runtime",
        "observability-diagnostics",
        "background-jobs-queues",
        "deployment-operations",
      ],
    },
    {
      id: "interview-prep",
      title: "Interview Prep",
      description: "Senior-level system design, all theory questions an interviewer will ask, plus 10 code challenges with hidden solutions to drill before your interview.",
      routeSlugs: [
        "senior-system-design",
        "interview-prep",
        "interview-01-node-fundamentals",
        "interview-02-event-loop",
        "interview-03-promises-async",
        "interview-04-express-fundamentals",
        "interview-05-rest-api-design",
        "interview-06-auth",
        "interview-07-security",
        "interview-08-databases",
        "interview-09-architecture",
        "interview-10-testing",
      ],
    },
  ],
};

export default manifest;
