import type { AcademyManifest } from "@/lib/types/academy";

const manifest: AcademyManifest = {
  slug: "typescript-mastery",
  title: "TypeScript Mastery",
  description:
    "Go beyond the basics — structural typing, generics, utility types, mapped and conditional types, and the advanced patterns that separate TypeScript experts from beginners.",
  version: "1.0.0",
  icon: "🔷",
  accentColor: "#3b82f6",
  totalEstimatedMinutes: 370,
  routes: [
    {
      slug: "the-type-system",
      title: "The Type System",
      order: 0,
      estimatedMinutes: 20,
      tags: ["typescript", "fundamentals"],
      component: () => import("./modules/the-type-system"),
    },
    {
      slug: "types-and-interfaces",
      title: "Types & Interfaces",
      order: 1,
      estimatedMinutes: 25,
      tags: ["typescript", "interfaces"],
      component: () => import("./modules/types-and-interfaces"),
    },
    {
      slug: "generics",
      title: "Generics",
      order: 2,
      estimatedMinutes: 30,
      tags: ["typescript", "generics"],
      component: () => import("./modules/generics"),
    },
    {
      slug: "utility-types",
      title: "Utility Types",
      order: 3,
      estimatedMinutes: 30,
      tags: ["typescript", "utility-types"],
      component: () => import("./modules/utility-types"),
    },
    {
      slug: "type-narrowing",
      title: "Type Narrowing",
      order: 4,
      estimatedMinutes: 25,
      tags: ["typescript", "narrowing"],
      component: () => import("./modules/type-narrowing"),
    },
    {
      slug: "mapped-types",
      title: "Mapped Types",
      order: 5,
      estimatedMinutes: 30,
      tags: ["typescript", "mapped-types"],
      component: () => import("./modules/mapped-types"),
    },
    {
      slug: "conditional-types",
      title: "Conditional Types",
      order: 6,
      estimatedMinutes: 35,
      tags: ["typescript", "conditional-types", "infer"],
      component: () => import("./modules/conditional-types"),
    },
    {
      slug: "advanced-patterns",
      title: "Advanced Patterns",
      order: 7,
      estimatedMinutes: 25,
      tags: ["typescript", "advanced", "satisfies"],
      component: () => import("./modules/advanced-patterns"),
    },
    {
      slug: "classes",
      title: "Classes in TypeScript",
      order: 8,
      estimatedMinutes: 35,
      tags: ["typescript", "classes", "oop", "access-modifiers", "abstract"],
      component: () => import("./modules/classes"),
    },
    {
      slug: "enums",
      title: "Enums & Literal Types",
      order: 9,
      estimatedMinutes: 25,
      tags: ["typescript", "enums", "union-types", "const-enum"],
      component: () => import("./modules/enums"),
    },
    {
      slug: "async-typescript",
      title: "Async TypeScript",
      order: 10,
      estimatedMinutes: 35,
      tags: ["typescript", "async", "promises", "awaited", "error-handling"],
      component: () => import("./modules/async-typescript"),
    },
    {
      slug: "tsconfig",
      title: "tsconfig.json Deep Dive",
      order: 11,
      estimatedMinutes: 30,
      tags: ["typescript", "tsconfig", "configuration", "strict", "module-resolution"],
      component: () => import("./modules/tsconfig"),
    },
    {
      slug: "function-overloads",
      title: "Function Overloads",
      order: 12,
      estimatedMinutes: 25,
      tags: ["typescript", "overloads", "function-signatures"],
      component: () => import("./modules/function-overloads"),
    },
  ],
  learningPath: [
    "the-type-system",
    "types-and-interfaces",
    "generics",
    "utility-types",
    "type-narrowing",
    "mapped-types",
    "conditional-types",
    "advanced-patterns",
    "classes",
    "enums",
    "async-typescript",
    "tsconfig",
    "function-overloads",
  ],
  groups: [
    {
      id: "typescript-foundations",
      title: "Type Foundations",
      description: "The core mental model behind TypeScript's structural type system.",
      routeSlugs: ["the-type-system", "types-and-interfaces"],
    },
    {
      id: "type-construction",
      title: "Reusable Type Construction",
      description: "Building stronger reusable abstractions with generics, utility types, narrowing, and mapped types.",
      routeSlugs: ["generics", "utility-types", "type-narrowing", "mapped-types"],
    },
    {
      id: "advanced-inference-patterns",
      title: "Advanced Inference & Patterns",
      description: "Conditional typing, inference, and advanced design patterns for large codebases.",
      routeSlugs: ["conditional-types", "advanced-patterns"],
    },
    {
      id: "backend-interview-prep",
      title: "Backend Interview Prep",
      description: "Classes, enums, async patterns, configuration, and function overloads — the topics backend interviewers probe most.",
      routeSlugs: ["classes", "enums", "async-typescript", "tsconfig", "function-overloads"],
    },
  ],
};

export default manifest;
