import type { AcademyManifest } from "@/lib/types/academy";

const manifest: AcademyManifest = {
  slug: "web-components",
  title: "Web Components",
  description:
    "Understand the platform-native component model. Custom Elements, Shadow DOM, HTML Templates, slots, lifecycle callbacks, and how Web Components interop with React and modern frameworks.",
  version: "1.0.0",
  icon: "🧩",
  accentColor: "#f97316",
  totalEstimatedMinutes: 165,
  routes: [
    {
      slug: "what-are-web-components",
      title: "What Are Web Components?",
      component: () => import("./modules/what-are-web-components"),
      estimatedMinutes: 20,
      tags: ["web-components", "fundamentals"],
      order: 0,
      keywords: [
        "custom elements",
        "shadow DOM",
        "html templates",
        "es modules",
        "browser native",
        "framework agnostic",
        "platform primitives",
        "reusable elements",
      ],
    },
    {
      slug: "custom-elements",
      title: "Custom Elements",
      component: () => import("./modules/custom-elements"),
      estimatedMinutes: 35,
      tags: ["web-components", "custom-elements", "lifecycle"],
      order: 1,
      keywords: [
        "customElements.define",
        "connectedCallback",
        "disconnectedCallback",
        "attributeChangedCallback",
        "adoptedCallback",
        "observedAttributes",
        "lifecycle callbacks",
        "element upgrade",
        "autonomous custom elements",
        "customized built-ins",
        "HTMLElement",
      ],
    },
    {
      slug: "shadow-dom",
      title: "Shadow DOM",
      component: () => import("./modules/shadow-dom"),
      estimatedMinutes: 35,
      tags: ["web-components", "shadow-dom", "css"],
      order: 2,
      keywords: [
        "shadow root",
        "shadow host",
        "style encapsulation",
        "attachShadow",
        "open mode",
        "closed mode",
        "CSS custom properties",
        "::part()",
        "::slotted()",
        ":host",
        "style scoping",
        "shadow boundary",
      ],
    },
    {
      slug: "html-templates-and-slots",
      title: "HTML Templates & Slots",
      component: () => import("./modules/html-templates-and-slots"),
      estimatedMinutes: 30,
      tags: ["web-components", "templates", "slots", "composition"],
      order: 3,
      keywords: [
        "template element",
        "cloneNode",
        "DocumentFragment",
        "slot projection",
        "named slots",
        "default slot",
        "slotchange event",
        "assignedElements",
        "content distribution",
        "fallback content",
        "::slotted",
      ],
    },
    {
      slug: "web-components-and-react",
      title: "Web Components & React",
      component: () => import("./modules/web-components-and-react"),
      estimatedMinutes: 30,
      tags: ["web-components", "react", "interop"],
      order: 4,
      keywords: [
        "React interop",
        "attribute vs property",
        "React 18 web components",
        "React 19 web components",
        "wrapper pattern",
        "custom events React",
        "ReactDOM.createRoot shadowRoot",
        "setAttribute vs property",
        "web components JSX",
      ],
    },
    {
      slug: "web-components-in-practice",
      title: "Web Components in Practice",
      component: () => import("./modules/web-components-in-practice"),
      estimatedMinutes: 35,
      tags: ["web-components", "lit", "design-system", "accessibility"],
      order: 5,
      keywords: [
        "Lit",
        "LitElement",
        "design system",
        "framework agnostic",
        "ElementInternals",
        "form associated",
        "focus delegation",
        "ARIA shadow DOM",
        "web component accessibility",
        "when to use web components",
        "lit vs react",
        "design tokens",
      ],
    },
  ],
  learningPath: [
    "what-are-web-components",
    "custom-elements",
    "shadow-dom",
    "html-templates-and-slots",
    "web-components-and-react",
    "web-components-in-practice",
  ],
  groups: [
    {
      id: "wc-foundations",
      title: "Platform Foundations",
      description: "The four specs, lifecycle, and DOM encapsulation",
      routeSlugs: ["what-are-web-components", "custom-elements", "shadow-dom"],
    },
    {
      id: "wc-advanced",
      title: "Composition & Integration",
      description: "Slots, React interop, real-world patterns, and Lit",
      routeSlugs: [
        "html-templates-and-slots",
        "web-components-and-react",
        "web-components-in-practice",
      ],
    },
  ],
};

export default manifest;
