import type { AcademyManifest } from "@/lib/types/academy";

const manifest: AcademyManifest = {
  slug: "react-deep-dive",
  title: "React Deep Dive",
  description:
    "Go beyond the API surface — understand how React actually works. Rendering, reconciliation, concurrent features, React 19, and the patterns that separate competent React developers from great ones.",
  version: "1.0.0",
  icon: "⚛️",
  accentColor: "#06b6d4",
  totalEstimatedMinutes: 435,
  routes: [
    {
      slug: "rendering-model",
      title: "The Rendering Model",
      order: 0,
      estimatedMinutes: 25,
      tags: ["react", "rendering", "reconciliation"],
      component: () => import("./modules/rendering-model"),
    },
    {
      slug: "use-state-use-reducer",
      title: "useState & useReducer",
      order: 1,
      estimatedMinutes: 25,
      tags: ["react", "hooks", "state"],
      component: () => import("./modules/use-state-use-reducer"),
    },
    {
      slug: "use-effect-in-depth",
      title: "useEffect In Depth",
      order: 2,
      estimatedMinutes: 30,
      tags: ["react", "hooks", "effects", "synchronization"],
      component: () => import("./modules/use-effect-in-depth"),
    },
    {
      slug: "use-ref-use-memo-use-callback",
      title: "useRef, useMemo & useCallback",
      order: 3,
      estimatedMinutes: 25,
      tags: ["react", "hooks", "performance", "memoization"],
      component: () => import("./modules/use-ref-use-memo-use-callback"),
    },
    {
      slug: "context-in-depth",
      title: "Context In Depth",
      order: 4,
      estimatedMinutes: 25,
      tags: ["react", "context", "state", "performance"],
      component: () => import("./modules/context-in-depth"),
    },
    {
      slug: "external-state-management",
      title: "External State Management",
      order: 5,
      estimatedMinutes: 30,
      tags: ["react", "state", "tanstack-query", "zustand", "url-state"],
      component: () => import("./modules/external-state-management"),
    },
    {
      slug: "custom-hooks",
      title: "Custom Hooks",
      order: 6,
      estimatedMinutes: 25,
      tags: ["react", "hooks", "patterns", "composition"],
      component: () => import("./modules/custom-hooks"),
    },
    {
      slug: "suspense-and-data-fetching",
      title: "Suspense & Data Fetching",
      order: 7,
      estimatedMinutes: 30,
      tags: ["react", "suspense", "data-fetching", "error-boundaries"],
      component: () => import("./modules/suspense-and-data-fetching"),
    },
    {
      slug: "concurrent-features",
      title: "Concurrent Features",
      order: 8,
      estimatedMinutes: 30,
      tags: ["react", "concurrent", "transitions", "performance"],
      component: () => import("./modules/concurrent-features"),
    },
    {
      slug: "react-19",
      title: "React 19",
      order: 9,
      estimatedMinutes: 25,
      tags: ["react", "react-19", "server-actions", "use-hook"],
      component: () => import("./modules/react-19"),
    },
    {
      slug: "component-patterns",
      title: "Component Patterns",
      order: 10,
      estimatedMinutes: 25,
      tags: ["react", "patterns", "compound-components", "composition"],
      component: () => import("./modules/component-patterns"),
    },
    {
      slug: "typescript-and-react",
      title: "TypeScript & React Patterns",
      order: 11,
      estimatedMinutes: 30,
      tags: ["react", "typescript", "generics", "types", "polymorphic"],
      component: () => import("./modules/typescript-and-react"),
    },
    {
      slug: "performance-and-profiling",
      title: "Performance & Profiling",
      order: 12,
      estimatedMinutes: 35,
      tags: ["react", "performance", "profiling", "memoization", "virtualization", "web-vitals"],
      component: () => import("./modules/performance-and-profiling"),
    },
    {
      slug: "testing-react-applications",
      title: "Testing React Applications",
      order: 13,
      estimatedMinutes: 35,
      tags: ["react", "testing", "rtl", "msw", "vitest", "unit-tests"],
      component: () => import("./modules/testing-react-applications"),
    },
    {
      slug: "interview-challenges",
      title: "Interview Challenges",
      order: 14,
      estimatedMinutes: 410,
      tags: ["react", "interviews", "challenge-bank", "forms", "tables", "performance"],
      component: () => import("./modules/interview-challenges"),
    },
  ],
  learningPath: [
    "rendering-model",
    "use-state-use-reducer",
    "use-effect-in-depth",
    "use-ref-use-memo-use-callback",
    "context-in-depth",
    "external-state-management",
    "custom-hooks",
    "suspense-and-data-fetching",
    "concurrent-features",
    "react-19",
    "component-patterns",
    "typescript-and-react",
    "performance-and-profiling",
    "testing-react-applications",
    "interview-challenges",
  ],
  groups: [
    {
      id: "react-foundations",
      title: "Render & State Foundations",
      description: "The mental models behind rendering, state snapshots, effects, and memoization.",
      routeSlugs: [
        "rendering-model",
        "use-state-use-reducer",
        "use-effect-in-depth",
        "use-ref-use-memo-use-callback",
      ],
    },
    {
      id: "react-coordination",
      title: "Coordination & Modern React",
      description: "Sharing state, extracting logic, async boundaries, and modern concurrent React features.",
      routeSlugs: [
        "context-in-depth",
        "external-state-management",
        "custom-hooks",
        "suspense-and-data-fetching",
        "concurrent-features",
        "react-19",
      ],
    },
    {
      id: "react-architecture-practice",
      title: "Architecture & Interview Practice",
      description: "Component API design and realistic React interview challenges.",
      routeSlugs: ["component-patterns", "typescript-and-react", "performance-and-profiling", "testing-react-applications", "interview-challenges"],
    },
  ],
};

export default manifest;
