import type { AcademyManifest } from "@/lib/types/academy";

const manifest: AcademyManifest = {
  slug: "nextjs-mastery",
  title: "Next.js Mastery",
  description:
    "Complete Next.js reference for both App Router and Pages Router. Rendering strategies, caching, Server Components, Server Actions, streaming, PPR, state management, database patterns, TypeScript types, error handling, env vars, next.config deep dive, auth, testing, i18n, and the interview answers senior engineers are expected to know.",
  version: "2.0.0",
  icon: "▲",
  accentColor: "#171717",
  totalEstimatedMinutes: 995,
  routes: [
    {
      slug: "app-router-fundamentals",
      title: "App Router Fundamentals",
      order: 0,
      estimatedMinutes: 40,
      tags: ["nextjs", "routing", "layouts"],
      component: () => import("./modules/app-router-fundamentals"),
    },
    {
      slug: "server-components-vs-client-components",
      title: "Server Components vs Client Components",
      order: 1,
      estimatedMinutes: 45,
      tags: ["nextjs", "rsc", "components"],
      component: () =>
        import("./modules/server-components-vs-client-components"),
    },
    {
      slug: "routing-advanced",
      title: "Advanced Routing",
      order: 2,
      estimatedMinutes: 40,
      tags: ["nextjs", "routing", "middleware"],
      component: () => import("./modules/routing-advanced"),
    },
    {
      slug: "rendering-strategies",
      title: "Rendering Strategies — SSR, SSG, ISR, CSR",
      order: 3,
      estimatedMinutes: 45,
      tags: ["nextjs", "ssr", "ssg", "isr", "csr", "rendering"],
      component: () => import("./modules/rendering-strategies"),
    },
    {
      slug: "streaming-and-suspense",
      title: "Streaming & Suspense",
      order: 4,
      estimatedMinutes: 40,
      tags: ["nextjs", "streaming", "suspense", "loading"],
      component: () => import("./modules/streaming-and-suspense"),
    },
    {
      slug: "partial-prerendering",
      title: "Partial Prerendering (PPR)",
      order: 5,
      estimatedMinutes: 35,
      tags: ["nextjs", "ppr", "rendering", "nextjs-15"],
      component: () => import("./modules/partial-prerendering"),
    },
    {
      slug: "data-fetching-and-caching",
      title: "Data Fetching & Caching",
      order: 6,
      estimatedMinutes: 50,
      tags: ["nextjs", "caching", "data-fetching"],
      component: () => import("./modules/data-fetching-and-caching"),
    },
    {
      slug: "server-actions",
      title: "Server Actions",
      order: 7,
      estimatedMinutes: 40,
      tags: ["nextjs", "server-actions", "mutations"],
      component: () => import("./modules/server-actions"),
    },
    {
      slug: "error-handling",
      title: "Error Handling",
      order: 8,
      estimatedMinutes: 40,
      tags: ["nextjs", "error-handling", "error-boundary", "not-found", "app-router"],
      component: () => import("./modules/error-handling"),
    },
    {
      slug: "state-management-app-router",
      title: "State Management with App Router",
      order: 9,
      estimatedMinutes: 40,
      tags: ["nextjs", "state", "zustand", "url-state", "swr", "react-query"],
      component: () => import("./modules/state-management-app-router"),
    },
    {
      slug: "database-patterns",
      title: "Database Patterns",
      order: 10,
      estimatedMinutes: 45,
      tags: ["nextjs", "database", "prisma", "drizzle", "serverless", "dal"],
      component: () => import("./modules/database-patterns"),
    },
    {
      slug: "nextjs-performance-and-optimization",
      title: "Performance & Optimization",
      order: 11,
      estimatedMinutes: 40,
      tags: ["nextjs", "performance", "optimization"],
      component: () =>
        import("./modules/nextjs-performance-and-optimization"),
    },
    {
      slug: "metadata-and-seo",
      title: "Metadata & SEO",
      order: 12,
      estimatedMinutes: 25,
      tags: ["nextjs", "seo", "metadata"],
      component: () => import("./modules/metadata-and-seo"),
    },
    {
      slug: "authentication-and-middleware",
      title: "Authentication & Middleware",
      order: 13,
      estimatedMinutes: 45,
      tags: ["nextjs", "auth", "middleware", "security"],
      component: () => import("./modules/authentication-and-middleware"),
    },
    {
      slug: "deployment-and-edge",
      title: "Deployment & Edge",
      order: 14,
      estimatedMinutes: 35,
      tags: ["nextjs", "deployment", "edge", "vercel"],
      component: () => import("./modules/deployment-and-edge"),
    },
    {
      slug: "environment-variables-and-config",
      title: "Environment Variables & Configuration",
      order: 15,
      estimatedMinutes: 30,
      tags: ["nextjs", "env", "config", "security", "build"],
      component: () => import("./modules/environment-variables-and-config"),
    },
    {
      slug: "nextjs-config-deep-dive",
      title: "next.config.ts Deep Dive",
      order: 16,
      estimatedMinutes: 35,
      tags: ["nextjs", "config", "redirects", "rewrites", "headers", "webpack"],
      component: () => import("./modules/nextjs-config-deep-dive"),
    },
    {
      slug: "route-handlers-advanced",
      title: "Route Handlers — CORS, Streaming, Webhooks",
      order: 17,
      estimatedMinutes: 40,
      tags: ["nextjs", "route-handlers", "cors", "webhooks", "sse", "api"],
      component: () => import("./modules/route-handlers-advanced"),
    },
    {
      slug: "pages-router-and-migration",
      title: "Pages Router & Migration to App Router",
      order: 18,
      estimatedMinutes: 50,
      tags: ["nextjs", "pages-router", "migration", "ssr", "ssg"],
      component: () => import("./modules/pages-router-and-migration"),
    },
    {
      slug: "route-segment-config",
      title: "Route Segment Config",
      order: 19,
      estimatedMinutes: 35,
      tags: ["nextjs", "rendering", "caching", "config"],
      component: () => import("./modules/route-segment-config"),
    },
    {
      slug: "navigation-hooks",
      title: "Navigation Hooks & App Router Navigation",
      order: 20,
      estimatedMinutes: 30,
      tags: ["nextjs", "navigation", "hooks", "app-router"],
      component: () => import("./modules/navigation-hooks"),
    },
    {
      slug: "typescript-in-nextjs",
      title: "TypeScript in Next.js",
      order: 21,
      estimatedMinutes: 35,
      tags: ["nextjs", "typescript", "types", "typed-routes"],
      component: () => import("./modules/typescript-in-nextjs"),
    },
    {
      slug: "internationalization",
      title: "Internationalization (i18n)",
      order: 22,
      estimatedMinutes: 35,
      tags: ["nextjs", "i18n", "localization", "middleware"],
      component: () => import("./modules/internationalization"),
    },
    {
      slug: "nextjs-15-and-observability",
      title: "Next.js 15 APIs & Observability",
      order: 23,
      estimatedMinutes: 35,
      tags: ["nextjs", "nextjs-15", "observability", "instrumentation", "after"],
      component: () => import("./modules/nextjs-15-and-observability"),
    },
    {
      slug: "testing-nextjs",
      title: "Testing Next.js Applications",
      order: 24,
      estimatedMinutes: 45,
      tags: ["nextjs", "testing", "vitest", "jest", "server-components"],
      component: () => import("./modules/testing-nextjs"),
    },
    {
      slug: "nextjs-interview-questions",
      title: "Next.js Interview Questions",
      order: 25,
      estimatedMinutes: 60,
      tags: ["nextjs", "interview", "questions"],
      component: () => import("./modules/nextjs-interview-questions"),
    },
  ],
  learningPath: [
    "app-router-fundamentals",
    "server-components-vs-client-components",
    "routing-advanced",
    "rendering-strategies",
    "streaming-and-suspense",
    "partial-prerendering",
    "data-fetching-and-caching",
    "server-actions",
    "error-handling",
    "state-management-app-router",
    "database-patterns",
    "nextjs-performance-and-optimization",
    "metadata-and-seo",
    "authentication-and-middleware",
    "deployment-and-edge",
    "environment-variables-and-config",
    "nextjs-config-deep-dive",
    "route-handlers-advanced",
    "pages-router-and-migration",
    "route-segment-config",
    "navigation-hooks",
    "typescript-in-nextjs",
    "internationalization",
    "nextjs-15-and-observability",
    "testing-nextjs",
    "nextjs-interview-questions",
  ],
  groups: [
    {
      id: "app-router-foundations",
      title: "App Router Foundations",
      description:
        "File-based routing, the Server/Client Component split, advanced routing patterns, and how rendering strategies work across both routers.",
      routeSlugs: [
        "app-router-fundamentals",
        "server-components-vs-client-components",
        "routing-advanced",
        "rendering-strategies",
      ],
    },
    {
      id: "rendering-and-streaming",
      title: "Rendering & Streaming",
      description:
        "Streaming with Suspense, loading.tsx vs manual Suspense boundaries, Partial Prerendering — how to make pages fast without sacrificing freshness.",
      routeSlugs: [
        "streaming-and-suspense",
        "partial-prerendering",
      ],
    },
    {
      id: "data-and-mutations",
      title: "Data, Mutations & State",
      description:
        "The 4-layer cache model, Server Actions, error handling, state management patterns (Zustand, URL state, SWR), and database integration with Prisma and Drizzle.",
      routeSlugs: [
        "data-fetching-and-caching",
        "server-actions",
        "error-handling",
        "state-management-app-router",
        "database-patterns",
      ],
    },
    {
      id: "production-patterns",
      title: "Production Patterns",
      description:
        "Performance primitives, metadata and SEO, authentication with middleware, deployment, environment variables, next.config.ts deep dive, and advanced Route Handler patterns.",
      routeSlugs: [
        "nextjs-performance-and-optimization",
        "metadata-and-seo",
        "authentication-and-middleware",
        "deployment-and-edge",
        "environment-variables-and-config",
        "nextjs-config-deep-dive",
        "route-handlers-advanced",
      ],
    },
    {
      id: "legacy-and-migration",
      title: "Pages Router & Migration",
      description:
        "The complete Pages Router surface — getServerSideProps, getStaticProps, ISR, API routes, useRouter — and the incremental migration path to the App Router.",
      routeSlugs: ["pages-router-and-migration"],
    },
    {
      id: "advanced-patterns-modern-nextjs",
      title: "Advanced Patterns & Modern Next.js",
      description:
        "Route segment config, navigation hooks, TypeScript type utilities for both routers, internationalization, and everything that changed in Next.js 15.",
      routeSlugs: [
        "route-segment-config",
        "navigation-hooks",
        "typescript-in-nextjs",
        "internationalization",
        "nextjs-15-and-observability",
      ],
    },
    {
      id: "testing",
      title: "Testing",
      description:
        "How to test every Next.js primitive: Server Components, Client Components, Route Handlers, Server Actions, and middleware.",
      routeSlugs: ["testing-nextjs"],
    },
    {
      id: "interview-prep",
      title: "Interview Prep",
      description:
        "30+ interview questions with ideal answers covering every major Next.js topic senior engineers are expected to know.",
      routeSlugs: ["nextjs-interview-questions"],
    },
  ],
};

export default manifest;
