import type { AcademyManifest } from "@/lib/types/academy";

const manifest: AcademyManifest = {
  slug: "design-systems",
  title: "Design Systems",
  description:
    "From zero to hero on frontend design systems. Tokens, component architecture, theming, styling technologies, accessibility, Storybook, monorepo distribution, versioning, testing, Figma workflows, governance, real-world case studies, and a from-scratch capstone.",
  version: "1.0.0",
  icon: "🎨",
  accentColor: "#8b5cf6",
  totalEstimatedMinutes: 1175,
  routes: [
    {
      slug: "what-is-a-design-system",
      title: "What Is a Design System?",
      component: () => import("./modules/what-is-a-design-system"),
      estimatedMinutes: 30,
      tags: ["design-systems", "foundations"],
      order: 0,
      keywords: [
        "design system definition",
        "component library",
        "style guide",
        "pattern library",
        "single source of truth",
        "design language",
        "ROI",
        "anatomy of a design system",
        "design ops",
      ],
    },
    {
      slug: "design-tokens",
      title: "Design Tokens",
      component: () => import("./modules/design-tokens"),
      estimatedMinutes: 40,
      tags: ["design-systems", "tokens", "foundations"],
      order: 1,
      keywords: [
        "design tokens",
        "primitive tokens",
        "semantic tokens",
        "component tokens",
        "Style Dictionary",
        "token naming",
        "DTCG format",
        "CSS custom properties",
        "token tiers",
        "theming tokens",
      ],
    },
    {
      slug: "color-typography-and-spacing-systems",
      title: "Color, Typography & Spacing Systems",
      component: () => import("./modules/color-typography-and-spacing-systems"),
      estimatedMinutes: 40,
      tags: ["design-systems", "foundations", "visual"],
      order: 2,
      keywords: [
        "color scale",
        "type scale",
        "modular scale",
        "spacing scale",
        "WCAG contrast",
        "OKLCH",
        "perceptual color",
        "4-point grid",
        "8-point grid",
        "elevation",
        "fluid typography",
      ],
    },
    {
      slug: "atomic-design-methodology",
      title: "Atomic Design Methodology",
      component: () => import("./modules/atomic-design-methodology"),
      estimatedMinutes: 35,
      tags: ["design-systems", "foundations", "components"],
      order: 3,
      keywords: [
        "atomic design",
        "Brad Frost",
        "atoms molecules organisms",
        "templates pages",
        "component hierarchy",
        "composition",
        "component granularity",
        "design methodology",
      ],
    },
    {
      slug: "component-architecture-and-api-design",
      title: "Component Architecture & API Design",
      component: () => import("./modules/component-architecture-and-api-design"),
      estimatedMinutes: 45,
      tags: ["design-systems", "components", "architecture"],
      order: 4,
      keywords: [
        "component API",
        "variants",
        "compound components",
        "polymorphic component",
        "asChild",
        "controlled uncontrolled",
        "slots",
        "composition",
        "props design",
        "headless components",
        "cva",
      ],
    },
    {
      slug: "styling-strategies-and-technologies",
      title: "Styling Strategies & Technologies",
      component: () => import("./modules/styling-strategies-and-technologies"),
      estimatedMinutes: 45,
      tags: ["design-systems", "styling", "css"],
      order: 5,
      keywords: [
        "CSS-in-JS",
        "Tailwind",
        "CSS Modules",
        "vanilla-extract",
        "Panda CSS",
        "Stitches",
        "zero-runtime",
        "runtime CSS-in-JS",
        "atomic CSS",
        "styled-components",
        "emotion",
      ],
    },
    {
      slug: "theming-and-multi-brand",
      title: "Theming & Multi-Brand Architecture",
      component: () => import("./modules/theming-and-multi-brand"),
      estimatedMinutes: 40,
      tags: ["design-systems", "theming", "tokens"],
      order: 6,
      keywords: [
        "theming",
        "dark mode",
        "multi-brand",
        "white label",
        "CSS variables theming",
        "runtime theming",
        "theme switching",
        "color scheme",
        "prefers-color-scheme",
        "FOUC",
        "theme contract",
      ],
    },
    {
      slug: "accessibility-in-design-systems",
      title: "Accessibility in Design Systems",
      component: () => import("./modules/accessibility-in-design-systems"),
      estimatedMinutes: 45,
      tags: ["design-systems", "accessibility", "a11y"],
      order: 7,
      keywords: [
        "WCAG",
        "ARIA",
        "focus management",
        "focus trap",
        "Radix UI",
        "React Aria",
        "headless primitives",
        "keyboard navigation",
        "screen reader",
        "accessible name",
        "roving tabindex",
      ],
    },
    {
      slug: "documentation-and-storybook",
      title: "Documentation & Storybook",
      component: () => import("./modules/documentation-and-storybook"),
      estimatedMinutes: 40,
      tags: ["design-systems", "documentation", "storybook"],
      order: 8,
      keywords: [
        "Storybook",
        "stories",
        "CSF",
        "MDX docs",
        "autodocs",
        "controls",
        "args",
        "documentation site",
        "usage guidelines",
        "component playground",
        "Storybook addons",
      ],
    },
    {
      slug: "monorepo-build-and-distribution",
      title: "Monorepo, Build & Distribution",
      component: () => import("./modules/monorepo-build-and-distribution"),
      estimatedMinutes: 45,
      tags: ["design-systems", "monorepo", "build", "packaging"],
      order: 9,
      keywords: [
        "monorepo",
        "pnpm workspace",
        "Turborepo",
        "npm publishing",
        "package exports",
        "tree-shaking",
        "tsup",
        "bundling",
        "ESM CJS",
        "peer dependencies",
        "side effects",
      ],
    },
    {
      slug: "versioning-and-releases",
      title: "Versioning & Releases",
      component: () => import("./modules/versioning-and-releases"),
      estimatedMinutes: 35,
      tags: ["design-systems", "versioning", "releases"],
      order: 10,
      keywords: [
        "semver",
        "Changesets",
        "breaking changes",
        "deprecation",
        "codemods",
        "migration guide",
        "changelog",
        "release strategy",
        "canary release",
        "semantic versioning",
      ],
    },
    {
      slug: "testing-design-systems",
      title: "Testing Design Systems",
      component: () => import("./modules/testing-design-systems"),
      estimatedMinutes: 40,
      tags: ["design-systems", "testing", "quality"],
      order: 11,
      keywords: [
        "visual regression",
        "Chromatic",
        "interaction tests",
        "Testing Library",
        "axe",
        "accessibility testing",
        "snapshot",
        "unit tests components",
        "play function",
        "Playwright component testing",
      ],
    },
    {
      slug: "figma-and-design-dev-workflow",
      title: "Figma & Design-Dev Workflow",
      component: () => import("./modules/figma-and-design-dev-workflow"),
      estimatedMinutes: 35,
      tags: ["design-systems", "figma", "workflow"],
      order: 12,
      keywords: [
        "Figma variables",
        "Tokens Studio",
        "design handoff",
        "Figma components",
        "auto layout",
        "design to code",
        "token sync",
        "Figma API",
        "single source of truth design",
        "dev mode",
      ],
    },
    {
      slug: "governance-contribution-and-adoption",
      title: "Governance, Contribution & Adoption",
      component: () => import("./modules/governance-contribution-and-adoption"),
      estimatedMinutes: 35,
      tags: ["design-systems", "governance", "process"],
      order: 13,
      keywords: [
        "governance model",
        "centralized federated",
        "RFC process",
        "contribution model",
        "adoption metrics",
        "design system team",
        "office hours",
        "deprecation policy",
        "design ops",
        "buy-in",
      ],
    },
    {
      slug: "case-studies-famous-design-systems",
      title: "Case Studies: Famous Design Systems",
      component: () => import("./modules/case-studies-famous-design-systems"),
      estimatedMinutes: 35,
      tags: ["design-systems", "case-studies"],
      order: 14,
      keywords: [
        "Material Design",
        "Shopify Polaris",
        "IBM Carbon",
        "Salesforce Lightning",
        "GitHub Primer",
        "Microsoft Fluent",
        "Atlassian Design System",
        "Adobe Spectrum",
        "Ant Design",
        "design system comparison",
      ],
    },
    {
      slug: "building-a-design-system-from-scratch",
      title: "Building a Design System From Scratch",
      component: () => import("./modules/building-a-design-system-from-scratch"),
      estimatedMinutes: 50,
      tags: ["design-systems", "capstone", "project"],
      order: 15,
      keywords: [
        "build design system",
        "capstone",
        "end to end",
        "tokens to components",
        "monorepo setup",
        "first component",
        "publish package",
        "design system roadmap",
        "MVP design system",
      ],
    },
    {
      slug: "layout-primitives",
      title: "Layout Primitives",
      component: () => import("./modules/layout-primitives"),
      estimatedMinutes: 45,
      tags: ["design-systems", "layout", "components"],
      order: 16,
      keywords: ["layout primitives", "Stack", "Cluster", "Grid", "Box", "Spacer", "Every Layout", "gap", "no margins", "flexbox grid"],
    },
    {
      slug: "forms-and-field-composition",
      title: "Forms & Field Composition",
      component: () => import("./modules/forms-and-field-composition"),
      estimatedMinutes: 50,
      tags: ["design-systems", "forms", "accessibility"],
      order: 17,
      keywords: ["form field", "label association", "aria-describedby", "aria-invalid", "ElementInternals", "form-associated", "React Hook Form", "Zod", "validation", "useId"],
    },
    {
      slug: "building-a-complex-component",
      title: "Building a Complex Component",
      component: () => import("./modules/building-a-complex-component"),
      estimatedMinutes: 55,
      tags: ["design-systems", "components", "accessibility"],
      order: 18,
      keywords: ["combobox", "dialog", "Radix", "React Aria", "aria-activedescendant", "headless", "interaction contract", "WAI-ARIA APG", "async search", "debounce"],
    },
    {
      slug: "icon-systems",
      title: "Icon Systems",
      component: () => import("./modules/icon-systems"),
      estimatedMinutes: 35,
      tags: ["design-systems", "icons", "build"],
      order: 19,
      keywords: ["SVG icons", "SVGR", "SVGO", "icon sprite", "currentColor", "tree-shaking icons", "icon font", "accessible icons", "aria-hidden"],
    },
    {
      slug: "motion-and-animation",
      title: "Motion & Animation",
      component: () => import("./modules/motion-and-animation"),
      estimatedMinutes: 40,
      tags: ["design-systems", "motion", "animation"],
      order: 20,
      keywords: ["motion tokens", "prefers-reduced-motion", "Framer Motion", "AnimatePresence", "exit animation", "starting-style", "allow-discrete", "easing", "transform opacity"],
    },
    {
      slug: "data-tables-and-complex-components",
      title: "Data Tables & Complex Components",
      component: () => import("./modules/data-tables-and-complex-components"),
      estimatedMinutes: 55,
      tags: ["design-systems", "components", "data"],
      order: 21,
      keywords: ["data table", "TanStack Table", "virtualization", "TanStack Virtual", "sorting", "pagination", "row selection", "table accessibility", "role grid", "responsive table"],
    },
    {
      slug: "responsive-and-container-queries",
      title: "Responsive & Container Queries",
      component: () => import("./modules/responsive-and-container-queries"),
      estimatedMinutes: 35,
      tags: ["design-systems", "responsive", "css"],
      order: 22,
      keywords: ["container queries", "@container", "breakpoint tokens", "viewport vs container", "cqi units", "fluid sizing", "clamp", "useBreakpoint", "intrinsic responsive"],
    },
    {
      slug: "i18n-rtl-and-bidi",
      title: "i18n, RTL & Bidi",
      component: () => import("./modules/i18n-rtl-and-bidi"),
      estimatedMinutes: 40,
      tags: ["design-systems", "i18n", "accessibility"],
      order: 23,
      keywords: ["internationalization", "RTL", "logical properties", "margin-inline-start", "dir rtl", "bidi", "bdi", "Intl", "text expansion", "icon mirroring", "localization"],
    },
    {
      slug: "ci-cd-pipelines",
      title: "CI/CD Pipelines",
      component: () => import("./modules/ci-cd-pipelines"),
      estimatedMinutes: 40,
      tags: ["design-systems", "ci-cd", "automation"],
      order: 24,
      keywords: ["GitHub Actions", "CI gates", "Chromatic CI", "size-limit", "bundle budget", "Changesets Action", "automated release", "Turborepo cache", "quality gates"],
    },
    {
      slug: "end-to-end-build-walkthrough",
      title: "End-to-End Build Walkthrough",
      component: () => import("./modules/end-to-end-build-walkthrough"),
      estimatedMinutes: 60,
      tags: ["design-systems", "capstone", "build"],
      order: 25,
      keywords: ["build design system step by step", "pnpm workspace", "Style Dictionary", "tsup", "Storybook", "Changesets publish", "monorepo scaffold", "first component", "vertical slice"],
    },
    {
      slug: "practical-toolkit-checklists-templates",
      title: "Practical Toolkit: Checklists & Templates",
      component: () => import("./modules/practical-toolkit-checklists-templates"),
      estimatedMinutes: 35,
      tags: ["design-systems", "process", "toolkit"],
      order: 26,
      keywords: ["definition of done", "accessibility checklist", "component spec template", "RFC template", "PR template", "API review checklist", "contribution process"],
    },
    {
      slug: "design-systems-interview-questions",
      title: "Design Systems Interview Questions",
      component: () => import("./modules/design-systems-interview-questions"),
      estimatedMinutes: 50,
      tags: ["design-systems", "interview", "questions"],
      order: 27,
      keywords: [
        "design system interview",
        "component API interview",
        "token architecture interview",
        "theming interview",
        "accessibility interview",
        "versioning interview",
        "design system tradeoffs",
        "frontend architecture interview",
      ],
    },
  ],
  learningPath: [
    "what-is-a-design-system",
    "design-tokens",
    "color-typography-and-spacing-systems",
    "atomic-design-methodology",
    "component-architecture-and-api-design",
    "styling-strategies-and-technologies",
    "theming-and-multi-brand",
    "accessibility-in-design-systems",
    "documentation-and-storybook",
    "monorepo-build-and-distribution",
    "versioning-and-releases",
    "testing-design-systems",
    "figma-and-design-dev-workflow",
    "governance-contribution-and-adoption",
    "case-studies-famous-design-systems",
    "building-a-design-system-from-scratch",
    "layout-primitives",
    "forms-and-field-composition",
    "building-a-complex-component",
    "icon-systems",
    "motion-and-animation",
    "data-tables-and-complex-components",
    "responsive-and-container-queries",
    "i18n-rtl-and-bidi",
    "ci-cd-pipelines",
    "end-to-end-build-walkthrough",
    "practical-toolkit-checklists-templates",
    "design-systems-interview-questions",
  ],
  groups: [
    {
      id: "ds-foundations",
      title: "Foundations",
      description:
        "What a design system is, the token layer that powers it, the color/type/spacing scales that give it visual coherence, and the Atomic Design model for structuring components.",
      routeSlugs: [
        "what-is-a-design-system",
        "design-tokens",
        "color-typography-and-spacing-systems",
        "atomic-design-methodology",
      ],
    },
    {
      id: "ds-component-engineering",
      title: "Component Engineering",
      description:
        "Designing component APIs, choosing a styling technology, building multi-brand theming, and baking in accessibility.",
      routeSlugs: [
        "component-architecture-and-api-design",
        "styling-strategies-and-technologies",
        "theming-and-multi-brand",
        "accessibility-in-design-systems",
      ],
    },
    {
      id: "ds-tooling-distribution",
      title: "Tooling & Distribution",
      description:
        "Documenting with Storybook, shipping packages from a monorepo, versioning safely, and testing at scale.",
      routeSlugs: [
        "documentation-and-storybook",
        "monorepo-build-and-distribution",
        "versioning-and-releases",
        "testing-design-systems",
      ],
    },
    {
      id: "ds-process-practice",
      title: "Process & Practice",
      description:
        "The Figma-to-code pipeline, governance and adoption, lessons from famous design systems, and a from-scratch strategic roadmap.",
      routeSlugs: [
        "figma-and-design-dev-workflow",
        "governance-contribution-and-adoption",
        "case-studies-famous-design-systems",
        "building-a-design-system-from-scratch",
      ],
    },
    {
      id: "ds-practitioner-build",
      title: "Practitioner: Building Components",
      description:
        "Hands-on, fully-coded builds: layout primitives, accessible forms, a complex component on a headless base, icon systems, motion, and data tables.",
      routeSlugs: [
        "layout-primitives",
        "forms-and-field-composition",
        "building-a-complex-component",
        "icon-systems",
        "motion-and-animation",
        "data-tables-and-complex-components",
      ],
    },
    {
      id: "ds-practitioner-ship",
      title: "Practitioner: Shipping & Operating",
      description:
        "Responsive/container queries, internationalization and RTL, CI/CD pipelines, a complete end-to-end build, and the checklists/templates that keep quality consistent.",
      routeSlugs: [
        "responsive-and-container-queries",
        "i18n-rtl-and-bidi",
        "ci-cd-pipelines",
        "end-to-end-build-walkthrough",
        "practical-toolkit-checklists-templates",
      ],
    },
    {
      id: "ds-interview",
      title: "Interview Prep",
      description: "Consolidated design-system interview questions across every topic, plus a system-design challenge.",
      routeSlugs: ["design-systems-interview-questions"],
    },
  ],
};

export default manifest;
