import MermaidDiagram from "@/components/diagrams/MermaidDiagram";
import { ArticleTable, InterviewPlaybook, InterviewChallenge, SolutionReveal, CodeBlock } from "@/components/ui";
import type { TocItem } from "@/lib/types/academy";

const docsLayersDiagram = String.raw`flowchart TD
  C["Component source"] --> S["Stories (CSF)<br/>every state + variant"]
  C --> TS["TS types"]
  S --> AD["Autodocs<br/>generated API table"]
  TS --> AD
  S --> PLAY["Interactive playground<br/>Controls / Args"]
  MDX["MDX guidelines<br/>do / don't, usage"] --> SITE["Docs site"]
  AD --> SITE
  PLAY --> SITE
  SITE --> USERS["Engineers & designers<br/>discover, learn, trust"]`;

const adoptionDiagram = String.raw`flowchart LR
  ND["No docs"] --> Q["Engineer has a question"]
  Q --> ASK["Asks DS team in Slack"]
  ASK --> BOT["Bottleneck: team is the docs"]
  GD["Good docs"] --> Q2["Engineer has a question"]
  Q2 --> SELF["Self-serves from docs site"]
  SELF --> SCALE["Adoption scales without<br/>scaling the team"]`;

export const toc: TocItem[] = [
  { id: "docs-are-the-product", title: "Docs Are Part of the Product", level: 2 },
  { id: "what-good-docs-cover", title: "What Good Docs Cover", level: 2 },
  { id: "storybook", title: "Storybook: The Workshop", level: 2 },
  { id: "csf", title: "Component Story Format (CSF)", level: 3 },
  { id: "controls-autodocs", title: "Controls & Autodocs", level: 3 },
  { id: "mdx", title: "MDX for Guidelines", level: 3 },
  { id: "addons", title: "Essential Addons", level: 2 },
  { id: "docs-site", title: "Storybook vs a Dedicated Docs Site", level: 2 },
  { id: "interview-framing", title: "Interview Framing", level: 2 },
  { id: "challenge", title: "Challenge", level: 2 },
  { id: "key-takeaways", title: "Key Takeaways", level: 2 },
];

export default function DocumentationAndStorybook() {
  return (
    <div className="article-content">
      <p>
        A component nobody can find, understand, or trust does not exist — adoption is gated by
        documentation. This is the most underrated truth about design systems: teams spend 90% of
        their effort on the components and 10% on docs, then wonder why adoption stalls. Treat
        documentation as a <strong>first-class part of the product</strong>, because for your users
        (other engineers and designers), the docs <em>are</em> the interface. This module covers
        what good docs contain and how Storybook became the industry-standard tool for building
        them.
      </p>

      <h2 id="docs-are-the-product">Docs Are Part of the Product</h2>
      <p>
        The economic argument is decisive: without docs, the design system team <em>becomes</em>{" "}
        the docs — every question routes through them in Slack, and adoption can&rsquo;t scale past
        the team&rsquo;s capacity to answer questions. With great docs, engineers self-serve and
        adoption scales independently of headcount.
      </p>

      <MermaidDiagram
        chart={adoptionDiagram}
        title="Docs as an adoption scaling lever"
        caption="Without docs, the team is the bottleneck; with docs, engineers self-serve and adoption scales without scaling the team."
        minHeight={340}
      />

      <h2 id="what-good-docs-cover">What Good Docs Cover</h2>
      <p>
        Comprehensive component docs answer four distinct questions, and weak docs usually only
        answer the first:
      </p>
      <ul>
        <li>
          <strong>What does it look like?</strong> — every variant, size, and state rendered live.
        </li>
        <li>
          <strong>How do I use it?</strong> — the full props/API reference, copy-pasteable code.
        </li>
        <li>
          <strong>When should I use it?</strong> — usage guidelines, <em>do/don&rsquo;t</em>{" "}
          examples, and which component to choose for a given problem (the most valuable and most
          often missing part).
        </li>
        <li>
          <strong>Does it behave correctly?</strong> — accessibility notes, keyboard behavior,
          edge cases.
        </li>
      </ul>

      <h2 id="storybook">Storybook: The Workshop</h2>
      <p>
        <strong>Storybook</strong> is the industry-standard tool for building and documenting
        components in isolation. It runs each component in a sandbox so you can develop and view
        every state without booting the whole app, and it doubles as the living documentation site.
        Its core unit is the <strong>story</strong>: a single rendered state of a component.
      </p>

      <MermaidDiagram
        chart={docsLayersDiagram}
        title="How Storybook assembles docs"
        caption="Stories plus TS types feed autogenerated API tables and an interactive playground; MDX adds prose guidelines — together they form the docs site."
        minHeight={460}
      />

      <h3 id="csf">Component Story Format (CSF)</h3>
      <p>
        Stories are written in <strong>Component Story Format</strong> — plain ES modules where the
        default export configures the component and named exports are individual stories. The
        discipline that matters: write a story for <em>every</em> meaningful state, including the
        ugly ones (loading, error, empty, long text, disabled). Stories are simultaneously docs,
        manual test cases, and visual-regression snapshots.
      </p>

      <CodeBlock
        code={`import type { Meta, StoryObj } from "@storybook/react";
import { Button } from "./Button";

const meta: Meta<typeof Button> = {
  title: "Components/Button",
  component: Button,
  args: { children: "Click me" },          // default args for all stories
  argTypes: { variant: { control: "select", options: ["primary", "secondary", "danger"] } },
};
export default meta;

type Story = StoryObj<typeof Button>;

export const Primary: Story = { args: { variant: "primary" } };
export const Danger: Story = { args: { variant: "danger" } };
export const Disabled: Story = { args: { disabled: true } };
export const Loading: Story = { args: { isLoading: true } };
export const LongLabel: Story = { args: { children: "A very long button label that wraps" } };`}
        lang="tsx"
        filename="Button.stories.tsx"
      />

      <h3 id="controls-autodocs">Controls & Autodocs</h3>
      <p>
        Two features turn stories into interactive docs. <strong>Controls</strong> render form
        inputs for each prop (driven by <code>argTypes</code> and inferred from TypeScript), letting
        anyone tweak props live — a playground without writing code. <strong>Autodocs</strong>{" "}
        generates an API reference table automatically from the component&rsquo;s TypeScript types
        and JSDoc comments, so your prop documentation can never drift from the actual types.
        Document props by writing good TS types and JSDoc, not separate markdown.
      </p>

      <CodeBlock
        code={`// Autodocs reads these JSDoc comments + types into the generated API table:
interface ButtonProps {
  /** Visual style of the button. */
  variant?: "primary" | "secondary" | "danger";
  /** Shows a spinner and disables interaction. */
  isLoading?: boolean;
}

// Enable autodocs globally in .storybook/preview.ts or per-meta:
const meta: Meta<typeof Button> = {
  component: Button,
  tags: ["autodocs"],   // generates a Docs page from stories + types
};`}
        lang="tsx"
        filename="autodocs.tsx"
      />

      <h3 id="mdx">MDX for Guidelines</h3>
      <p>
        Stories show the <em>what</em> and <em>how</em>; the <em>when</em> needs prose.{" "}
        <strong>MDX</strong> (Markdown + JSX) lets you write rich guideline pages that embed live
        stories alongside do/don&rsquo;t guidance — the highest-value documentation and the part
        that actually changes behavior.
      </p>

      <CodeBlock
        code={`import { Meta, Canvas } from "@storybook/blocks";
import * as ButtonStories from "./Button.stories";

<Meta of={ButtonStories} />

# Button

Use buttons for actions, never for navigation (use a link for navigation).

## When to use which variant
- **Primary** — the single most important action on a view. One per view.
- **Danger** — destructive actions; always pair with a confirmation.

<Canvas of={ButtonStories.Primary} />   {/* live, interactive example */}

> ❌ Don't use two primary buttons in the same view — it removes the hierarchy.`}
        lang="markdown"
        filename="Button.mdx"
      />

      <h2 id="addons">Essential Addons</h2>
      <ArticleTable
        caption="The Storybook addons most design systems consider mandatory."
        minWidth={780}
      >
        <table>
          <thead>
            <tr>
              <th>Addon</th>
              <th>What it does</th>
              <th>Why it matters</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><code>@storybook/addon-a11y</code></td>
              <td>Runs axe on each story</td>
              <td>Catches accessibility issues at authoring time</td>
            </tr>
            <tr>
              <td>Controls (built-in)</td>
              <td>Live prop editing</td>
              <td>Interactive playground, no code</td>
            </tr>
            <tr>
              <td>Interactions / play fn</td>
              <td>Scripted user interactions</td>
              <td>Stories double as interaction tests</td>
            </tr>
            <tr>
              <td>Viewport</td>
              <td>Responsive preview</td>
              <td>Verify components across breakpoints</td>
            </tr>
            <tr>
              <td>Chromatic</td>
              <td>Visual regression on stories</td>
              <td>Catches unintended visual changes in CI</td>
            </tr>
          </tbody>
        </table>
      </ArticleTable>

      <h2 id="docs-site">Storybook vs a Dedicated Docs Site</h2>
      <p>
        Large systems often run <em>both</em>: Storybook as the engineering workshop (every state,
        interaction tests, visual regression) and a polished marketing-quality docs site (Nextra,
        Docusaurus, or a custom Next.js site) for designers, PMs, and external consumers — pulling
        examples from the same stories. The principle either way: <strong>docs live next to the
        code and are generated from it</strong> wherever possible, so they can&rsquo;t go stale. Docs
        maintained by hand, separate from the source, always drift.
      </p>

      <h2 id="interview-framing">Interview Framing</h2>
      <InterviewPlaybook
        title="How to answer: 'How do you document a design system, and why does it matter?'"
        intro="The interviewer is checking whether you understand that docs drive adoption, not just whether you know Storybook exists."
        steps={[
          "Lead with the adoption argument: docs are first-class product; without them the team becomes the bottleneck and adoption can't scale.",
          "Name the four questions good docs answer: what it looks like, how to use it, WHEN to use it (most valuable), and how it behaves (a11y).",
          "Explain Storybook + CSF: a story per meaningful state (including loading/error/empty), doubling as docs, manual tests, and visual snapshots.",
          "Cover autodocs + controls: generate the API table from TS types so it can't drift, and use MDX for usage guidelines and do/don't.",
          "Emphasize: docs generated from the source stay in sync; hand-maintained separate docs always drift.",
        ]}
      />

      <InterviewChallenge
        title="Fix the stalled adoption"
        scenario={
          <>
            Your design system has 40 well-built, accessible components, but adoption is stuck at
            25%. Engineers say they &ldquo;can&rsquo;t tell which component to use,&rdquo;
            &ldquo;don&rsquo;t know the props,&rdquo; and &ldquo;keep pinging the DS team on
            Slack.&rdquo; The components are great; something else is broken.
          </>
        }
        tasks={[
          "Diagnose the root cause and explain why great components alone didn't drive adoption.",
          "Specify exactly what documentation you'd add and in what priority order.",
          "Explain how you'd keep the docs from going stale once built.",
        ]}
      />
      <SolutionReveal difficulty="medium">
          <p>
            <strong>Root cause: a documentation gap, not a component gap.</strong> The Slack
            questions map directly to missing docs — &ldquo;which component&rdquo; = missing usage
            guidelines, &ldquo;don&rsquo;t know props&rdquo; = missing API reference, &ldquo;keep
            pinging&rdquo; = no self-serve path. The team is acting as live documentation.
          </p>
          <p>
            <strong>Priority:</strong> (1) Autodocs API tables generated from TS types — fastest
            win, kills the &ldquo;what props&rdquo; questions immediately. (2) Stories for every
            state so engineers see behavior. (3) MDX usage guidelines with do/don&rsquo;t and a
            &ldquo;which component for which problem&rdquo; decision guide — this directly answers
            the &ldquo;which component&rdquo; complaint and is the highest-leverage prose. (4)
            Make the docs site discoverable (link from the package README, the repo, onboarding).
          </p>
          <p>
            <strong>Anti-staleness:</strong> generate API tables from types (autodocs), embed live
            stories in MDX (examples can&rsquo;t rot), run Chromatic so visual docs stay accurate,
            and add a &ldquo;docs updated&rdquo; check to the component PR template so new
            components ship with docs or don&rsquo;t ship.
          </p>
        </SolutionReveal>

      <h2 id="key-takeaways">Key Takeaways</h2>
      <ul>
        <li>
          Docs are a <strong>first-class part of the product</strong>; adoption is gated by
          documentation, not component quality alone.
        </li>
        <li>
          Good docs answer four questions: what it looks like, how to use it, <strong>when</strong>{" "}
          to use it, and how it behaves — the &ldquo;when&rdquo; is most valuable and most missing.
        </li>
        <li>
          <strong>Storybook + CSF</strong>: write a story per meaningful state; stories serve as
          docs, manual tests, and visual snapshots simultaneously.
        </li>
        <li>
          Use <strong>autodocs</strong> (API tables from TS types) and <strong>controls</strong>{" "}
          (live playground) so docs can&rsquo;t drift from the code.
        </li>
        <li>
          Write <strong>MDX guidelines</strong> with do/don&rsquo;t and decision guides for the
          highest-leverage prose docs.
        </li>
        <li>
          <strong>Generate docs from source</strong> — hand-maintained, separate docs always go
          stale.
        </li>
      </ul>
    </div>
  );
}
